import { Place } from "./types";

// All 51 venues from HydraDB — serves as local fallback + browse data
export const SAMPLE_PLACES: Place[] = [
  // === FOOD: Mexican ===
  {
    id: "la-taqueria",
    name: "La Taqueria",
    category: "food",
    subcategory: "Mexican",
    address: "2889 Mission St",
    neighborhood: "Mission District",
    description: "Legendary SF burrito, James Beard winner. Cash only, no rice in the burrito — just meat, beans, and perfection.",
    price_tier: 1,
    avg_price: 11,
    tags: ["cash-only", "local-icon", "burritos"],
    lat: 37.7509,
    lng: -122.4181,
    status: "approved",
    vote_count: 87,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "el-farolito",
    name: "El Farolito",
    category: "food",
    subcategory: "Mexican",
    address: "2779 Mission St",
    neighborhood: "Mission District",
    description: "Giant super burritos, open late. The go-to spot for a 2am burrito that'll last you two meals.",
    price_tier: 1,
    avg_price: 11,
    tags: ["late-night", "burritos", "local-icon"],
    lat: 37.7525,
    lng: -122.4183,
    status: "approved",
    vote_count: 72,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "taqueria-cancun",
    name: "Taqueria Cancun",
    category: "food",
    subcategory: "Mexican",
    address: "2288 Mission St",
    neighborhood: "Mission District",
    description: "Huge burritos under $11. Fast service, generous portions, and great salsa bar.",
    price_tier: 1,
    avg_price: 10,
    tags: ["burritos", "fast-service"],
    lat: 37.7583,
    lng: -122.4191,
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-12T00:00:00Z",
    updated_at: "2024-01-12T00:00:00Z",
  },
  {
    id: "taqueria-el-buen-sabor",
    name: "Taqueria El Buen Sabor",
    category: "food",
    subcategory: "Mexican",
    address: "699 Valencia St",
    neighborhood: "Mission District",
    description: "Under $10 burritos, authentic flavors. A neighborhood staple that never disappoints.",
    price_tier: 1,
    avg_price: 9,
    tags: ["burritos", "authentic"],
    lat: 37.7604,
    lng: -122.4216,
    status: "approved",
    vote_count: 33,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-14T00:00:00Z",
    updated_at: "2024-01-14T00:00:00Z",
  },

  // === FOOD: Mediterranean ===
  {
    id: "truly-mediterranean",
    name: "Truly Mediterranean",
    category: "food",
    subcategory: "Mediterranean",
    address: "3109 16th St",
    neighborhood: "Mission District",
    description: "Best falafel in the city under $10. BYOB friendly. The lamb shawarma is a must.",
    price_tier: 1,
    avg_price: 9,
    tags: ["falafel", "BYOB"],
    lat: 37.7649,
    lng: -122.4194,
    status: "approved",
    vote_count: 58,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "old-jerusalem",
    name: "Old Jerusalem",
    category: "food",
    subcategory: "Mediterranean",
    address: "2976 Mission St",
    neighborhood: "Mission District",
    description: "Authentic Middle Eastern, huge portions. Family-run with homemade everything.",
    price_tier: 1,
    avg_price: 12,
    tags: ["middle-eastern", "family-run"],
    lat: 37.7530,
    lng: -122.4180,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-16T00:00:00Z",
    updated_at: "2024-01-16T00:00:00Z",
  },
  {
    id: "sunrise-deli",
    name: "Sunrise Deli",
    category: "food",
    subcategory: "Mediterranean",
    address: "2115 Irving St",
    neighborhood: "Sunset",
    description: "Massive shawarma plates that feed two. Hidden gem in the Sunset.",
    price_tier: 1,
    avg_price: 11,
    tags: ["shawarma", "neighborhood-gem"],
    lat: 37.7637,
    lng: -122.4680,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-17T00:00:00Z",
    updated_at: "2024-01-17T00:00:00Z",
  },

  // === FOOD: Vietnamese ===
  {
    id: "saigon-sandwich",
    name: "Saigon Sandwich",
    category: "food",
    subcategory: "Vietnamese",
    address: "560 Larkin St",
    neighborhood: "Tenderloin",
    description: "Best banh mi in SF, legendary $5. Cash only, always a line, always worth it.",
    price_tier: 1,
    avg_price: 5,
    tags: ["cash-only", "local-icon", "banh-mi"],
    lat: 37.7833,
    lng: -122.4170,
    status: "approved",
    vote_count: 94,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "turtle-tower",
    name: "Turtle Tower",
    category: "food",
    subcategory: "Vietnamese",
    address: "645 Larkin St",
    neighborhood: "Tenderloin",
    description: "Authentic Northern Vietnamese pho. Clean, clear broth — the real thing.",
    price_tier: 1,
    avg_price: 13,
    tags: ["pho", "authentic"],
    lat: 37.7843,
    lng: -122.4166,
    status: "approved",
    vote_count: 41,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-18T00:00:00Z",
    updated_at: "2024-01-18T00:00:00Z",
  },
  {
    id: "pho-2000",
    name: "Pho 2000",
    category: "food",
    subcategory: "Vietnamese",
    address: "637 Larkin St",
    neighborhood: "Tenderloin",
    description: "Generous pho bowls at great prices. Quick service, solid flavors.",
    price_tier: 1,
    avg_price: 12,
    tags: ["pho", "quick-service"],
    lat: 37.7840,
    lng: -122.4167,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-19T00:00:00Z",
    updated_at: "2024-01-19T00:00:00Z",
  },
  {
    id: "hai-ky-mi-gia",
    name: "Hai Ky Mi Gia",
    category: "food",
    subcategory: "Vietnamese",
    address: "707 Ellis St",
    neighborhood: "Tenderloin",
    description: "Dry egg noodles, authentic Vietnamese-Chinese. A hidden gem for noodle lovers.",
    price_tier: 1,
    avg_price: 10,
    tags: ["noodles", "authentic"],
    lat: 37.7830,
    lng: -122.4152,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "bun-mee",
    name: "Bun Mee",
    category: "food",
    subcategory: "Vietnamese",
    address: "674 Geary St",
    neighborhood: "Tenderloin",
    description: "Modern banh mi, great combos. A step up from the classic with fun twists.",
    price_tier: 1,
    avg_price: 10,
    tags: ["banh-mi", "modern"],
    lat: 37.7862,
    lng: -122.4138,
    status: "approved",
    vote_count: 25,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-21T00:00:00Z",
    updated_at: "2024-01-21T00:00:00Z",
  },

  // === FOOD: Chinese ===
  {
    id: "good-mong-kok",
    name: "Good Mong Kok",
    category: "food",
    subcategory: "Chinese",
    address: "1039 Stockton St",
    neighborhood: "Chinatown",
    description: "Dim sum to-go, $3-5 boxes. Cash only, grab and go — perfect cheap breakfast.",
    price_tier: 1,
    avg_price: 4,
    tags: ["dim-sum", "cash-only", "bakery"],
    lat: 37.7948,
    lng: -122.4093,
    status: "approved",
    vote_count: 63,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-11T00:00:00Z",
    updated_at: "2024-01-11T00:00:00Z",
  },
  {
    id: "yin-du-wonton",
    name: "Yin Du Wonton",
    category: "food",
    subcategory: "Chinese",
    address: "731 Vallejo St",
    neighborhood: "Chinatown",
    description: "Hand-pulled noodles and wontons. Incredible textures at unbeatable prices.",
    price_tier: 1,
    avg_price: 9,
    tags: ["noodles", "wonton"],
    lat: 37.7979,
    lng: -122.4092,
    status: "approved",
    vote_count: 27,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-22T00:00:00Z",
    updated_at: "2024-01-22T00:00:00Z",
  },
  {
    id: "san-tung",
    name: "San Tung",
    category: "food",
    subcategory: "Chinese",
    address: "1031 Irving St",
    neighborhood: "Inner Sunset",
    description: "Famous dry-fried chicken wings that are worth the wait. Noodle dishes are solid too.",
    price_tier: 1,
    avg_price: 12,
    tags: ["dry-fried-chicken-wings", "noodles"],
    lat: 37.7637,
    lng: -122.4694,
    status: "approved",
    vote_count: 51,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-18T00:00:00Z",
    updated_at: "2024-01-18T00:00:00Z",
  },
  {
    id: "aa-bakery",
    name: "AA Bakery & Cafe",
    category: "food",
    subcategory: "Chinese",
    address: "1068 Stockton St",
    neighborhood: "Chinatown",
    description: "Egg tarts $1.50, pork buns $2, no frills. The best cheap snack in Chinatown.",
    price_tier: 1,
    avg_price: 3,
    tags: ["bakery", "egg-tarts", "bbq-pork-buns"],
    lat: 37.7953,
    lng: -122.4094,
    status: "approved",
    vote_count: 44,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-23T00:00:00Z",
    updated_at: "2024-01-23T00:00:00Z",
  },
  {
    id: "delicious-dim-sum",
    name: "Delicious Dim Sum",
    category: "food",
    subcategory: "Chinese",
    address: "752 Jackson St",
    neighborhood: "Chinatown",
    description: "Pork buns & shrimp dumplings $3-6, always a line. Worth every minute of the wait.",
    price_tier: 1,
    avg_price: 5,
    tags: ["dim-sum", "to-go", "cash-only"],
    lat: 37.7963,
    lng: -122.4074,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-25T00:00:00Z",
    updated_at: "2024-01-25T00:00:00Z",
  },
  {
    id: "house-of-pancakes",
    name: "House of Pancakes",
    category: "food",
    subcategory: "Chinese",
    address: "635 Jackson St",
    neighborhood: "Chinatown",
    description: "Scallion pancakes $4, pot stickers $6. Simple, cheap, and absolutely delicious.",
    price_tier: 1,
    avg_price: 6,
    tags: ["scallion-pancakes", "dumplings", "cash-only"],
    lat: 37.7959,
    lng: -122.4065,
    status: "approved",
    vote_count: 31,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-26T00:00:00Z",
    updated_at: "2024-01-26T00:00:00Z",
  },
  {
    id: "kingdom-of-dumpling",
    name: "Kingdom of Dumpling",
    category: "food",
    subcategory: "Chinese",
    address: "1713 Taraval St",
    neighborhood: "Sunset",
    description: "XLB and dumplings, Sunset favorite. The soup dumplings rival places twice the price.",
    price_tier: 1,
    avg_price: 10,
    tags: ["dumplings", "XLB"],
    lat: 37.7432,
    lng: -122.4831,
    status: "approved",
    vote_count: 39,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-27T00:00:00Z",
    updated_at: "2024-01-27T00:00:00Z",
  },

  // === FOOD: Other cuisines ===
  {
    id: "senor-sisig",
    name: "Senor Sisig",
    category: "food",
    subcategory: "Filipino",
    address: "Food trucks citywide",
    neighborhood: "SoMa",
    description: "Filipino fusion bowls and burritos. Unique SF flavor you can't get anywhere else.",
    price_tier: 1,
    avg_price: 11,
    tags: ["food-truck", "bowls", "fusion"],
    lat: 37.7620,
    lng: -122.4200,
    status: "approved",
    vote_count: 48,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-28T00:00:00Z",
    updated_at: "2024-01-28T00:00:00Z",
  },
  {
    id: "mandalay-restaurant",
    name: "Mandalay Restaurant",
    category: "food",
    subcategory: "Burmese",
    address: "4348 California St",
    neighborhood: "Richmond",
    description: "Tea leaf salad $10, unique Burmese food. One of the few Burmese restaurants in the city.",
    price_tier: 1,
    avg_price: 12,
    tags: ["burmese", "tea-leaf-salad"],
    lat: 37.7858,
    lng: -122.4629,
    status: "approved",
    vote_count: 26,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "pakwan",
    name: "Pakwan",
    category: "food",
    subcategory: "Indian/Pakistani",
    address: "3182 16th St",
    neighborhood: "Mission District",
    description: "Massive biryani plates under $12, BYOB. Pakistani comfort food at its best.",
    price_tier: 1,
    avg_price: 10,
    tags: ["pakistani", "biryani", "naan", "BYOB"],
    lat: 37.7651,
    lng: -122.4234,
    status: "approved",
    vote_count: 42,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-02T00:00:00Z",
    updated_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "udupi-palace",
    name: "Udupi Palace",
    category: "food",
    subcategory: "Indian",
    address: "1007 Valencia St",
    neighborhood: "Mission District",
    description: "Giant dosas $10-12, all vegetarian. South Indian heaven for veggie lovers.",
    price_tier: 1,
    avg_price: 11,
    tags: ["south-indian", "dosa", "vegetarian"],
    lat: 37.7561,
    lng: -122.4210,
    status: "approved",
    vote_count: 36,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-03T00:00:00Z",
    updated_at: "2024-02-03T00:00:00Z",
  },
  {
    id: "naan-n-curry",
    name: "Naan N Curry",
    category: "food",
    subcategory: "Indian",
    address: "336 O'Farrell St",
    neighborhood: "Tenderloin",
    description: "Cheap curry and naan, open super late. The late-night Indian spot everyone ends up at.",
    price_tier: 1,
    avg_price: 10,
    tags: ["late-night", "naan", "curry"],
    lat: 37.7860,
    lng: -122.4107,
    status: "approved",
    vote_count: 37,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-04T00:00:00Z",
    updated_at: "2024-02-04T00:00:00Z",
  },
  {
    id: "lers-ros",
    name: "Lers Ros Thai",
    category: "food",
    subcategory: "Thai",
    address: "730 Larkin St",
    neighborhood: "Tenderloin",
    description: "Best authentic Thai in SF, big portions. They don't tone down the spice.",
    price_tier: 1,
    avg_price: 12,
    tags: ["thai", "spicy", "authentic"],
    lat: 37.7831,
    lng: -122.4175,
    status: "approved",
    vote_count: 53,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-05T00:00:00Z",
    updated_at: "2024-02-05T00:00:00Z",
  },

  // === FOOD: Pizza ===
  {
    id: "costco-pizza",
    name: "Costco Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "450 10th St",
    neighborhood: "SoMa",
    description: "$1.99 slice, $9.95 whole pizza. You don't even need a membership for the food court.",
    price_tier: 1,
    avg_price: 2,
    tags: ["bulk", "value"],
    lat: 37.7700,
    lng: -122.4050,
    status: "approved",
    vote_count: 73,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "arinell-pizza",
    name: "Arinell Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "509 Valencia St",
    neighborhood: "Mission District",
    description: "Legit NY-style slices, $4-5 a slice. Thin crust done right.",
    price_tier: 1,
    avg_price: 5,
    tags: ["NY-style", "cash-friendly"],
    lat: 37.7621,
    lng: -122.4220,
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-08T00:00:00Z",
    updated_at: "2024-02-08T00:00:00Z",
  },
  {
    id: "golden-boy-pizza",
    name: "Golden Boy Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "542 Green St",
    neighborhood: "North Beach",
    description: "Thick focaccia-style, legendary late night. The clam & garlic slice is iconic.",
    price_tier: 1,
    avg_price: 5,
    tags: ["focaccia-style", "local-icon", "late-night"],
    lat: 37.7997,
    lng: -122.4074,
    status: "approved",
    vote_count: 66,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-09T00:00:00Z",
    updated_at: "2024-02-09T00:00:00Z",
  },

  // === FOOD: Other ===
  {
    id: "grubstake",
    name: "Grubstake",
    category: "food",
    subcategory: "Late Night",
    address: "1525 Pine St",
    neighborhood: "Nob Hill",
    description: "Late-night burgers in a converted train car. Portuguese specialties and classic diner vibes.",
    price_tier: 1,
    avg_price: 12,
    tags: ["late-night", "portuguese", "burgers"],
    lat: 37.7887,
    lng: -122.4207,
    status: "approved",
    vote_count: 34,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "ikes-sandwiches",
    name: "Ike's Love & Sandwiches",
    category: "food",
    subcategory: "Sandwiches",
    address: "Multiple SF locations",
    neighborhood: "SoMa",
    description: "Dutch crunch sandwiches, massive portions. The dirty sauce is legendary.",
    price_tier: 1,
    avg_price: 12,
    tags: ["sandwiches", "dutch-crunch", "local"],
    lat: 37.7749,
    lng: -122.4194,
    status: "approved",
    vote_count: 43,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-11T00:00:00Z",
    updated_at: "2024-02-11T00:00:00Z",
  },

  // === GROCERY ===
  {
    id: "grocery-outlet",
    name: "Grocery Outlet",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "Mission District",
    description: "40-60% off retail, name brands. Selection changes weekly — treasure hunt shopping.",
    price_tier: 1,
    avg_price: 30,
    tags: ["bargain", "treasure-hunt"],
    lat: 37.7700,
    lng: -122.4250,
    status: "approved",
    vote_count: 56,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "costco-sf",
    name: "Costco",
    category: "grocery",
    subcategory: "Warehouse",
    address: "450 10th St",
    neighborhood: "SoMa",
    description: "In-city Costco, bulk everything + $5 rotisserie chicken. Membership pays for itself.",
    price_tier: 1,
    avg_price: 50,
    tags: ["bulk", "membership"],
    lat: 37.7700,
    lng: -122.4050,
    status: "approved",
    vote_count: 68,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "smart-and-final",
    name: "Smart & Final",
    category: "grocery",
    subcategory: "Supermarket",
    address: "1245 South Van Ness",
    neighborhood: "Mission District",
    description: "Bulk pricing, no membership needed. Great for stocking up without a Costco card.",
    price_tier: 1,
    avg_price: 40,
    tags: ["bulk", "no-membership"],
    lat: 37.7565,
    lng: -122.4165,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-13T00:00:00Z",
    updated_at: "2024-02-13T00:00:00Z",
  },
  {
    id: "duc-loi",
    name: "Duc Loi Supermarket",
    category: "grocery",
    subcategory: "Asian Grocery",
    address: "2200 Mission St",
    neighborhood: "Mission District",
    description: "Amazing produce prices. Best Asian grocery selection in the Mission.",
    price_tier: 1,
    avg_price: 25,
    tags: ["asian-produce", "fresh"],
    lat: 37.7583,
    lng: -122.4191,
    status: "approved",
    vote_count: 37,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "trader-joes",
    name: "Trader Joe's",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "North Beach",
    description: "Great private-label products, good prices. Wine section is unbeatable value.",
    price_tier: 1,
    avg_price: 40,
    tags: ["value", "private-label", "wine"],
    lat: 37.8059,
    lng: -122.4148,
    status: "approved",
    vote_count: 62,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "safeway",
    name: "Safeway",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "Marina",
    description: "Club Card deals + gas rewards. Widespread in SF, reliable basics.",
    price_tier: 2,
    avg_price: 50,
    tags: ["chain", "rewards-program", "pharmacy"],
    lat: 37.7645,
    lng: -122.4320,
    status: "approved",
    vote_count: 21,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },

  // === BARS ===
  {
    id: "li-po-lounge",
    name: "Li Po Lounge",
    category: "bars",
    subcategory: "Dive Bar",
    address: "916 Grant Ave",
    neighborhood: "Chinatown",
    description: "Iconic dive, famous Chinese Mai Tai. Anthony Bourdain's SF favorite.",
    price_tier: 1,
    avg_price: 7,
    tags: ["dive-bar", "chinese-mai-tai"],
    lat: 37.7940,
    lng: -122.4076,
    status: "approved",
    vote_count: 59,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "the-500-club",
    name: "The 500 Club",
    category: "bars",
    subcategory: "Dive Bar",
    address: "500 Guerrero St",
    neighborhood: "Mission District",
    description: "Classic Mission dive, cheap wells, pool table. No pretense, just drinks.",
    price_tier: 1,
    avg_price: 7,
    tags: ["dive-bar", "pool-table"],
    lat: 37.7649,
    lng: -122.4236,
    status: "approved",
    vote_count: 44,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-21T00:00:00Z",
    updated_at: "2024-01-21T00:00:00Z",
  },
  {
    id: "toronado",
    name: "Toronado",
    category: "bars",
    subcategory: "Beer Bar",
    address: "547 Haight St",
    neighborhood: "Haight-Ashbury",
    description: "50+ craft beers on tap, SF institution. Cash only. The bartenders don't do cocktails.",
    price_tier: 1,
    avg_price: 8,
    tags: ["craft-beer", "local-icon"],
    lat: 37.7719,
    lng: -122.4296,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-22T00:00:00Z",
    updated_at: "2024-01-22T00:00:00Z",
  },

  // === GYM / FITNESS ===
  {
    id: "24-fitness-soma",
    name: "24 Hour Fitness - SoMa",
    category: "gym",
    subcategory: "Full Gym",
    address: "350 Bay St",
    neighborhood: "North Beach",
    description: "24/7 access, cardio, weights, group classes. One of the most affordable full-service gyms in SF.",
    price_tier: 2,
    avg_price: 35,
    tags: ["24-7", "classes", "cardio", "weights"],
    lat: 37.8058,
    lng: -122.4148,
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "24-fitness-fillmore",
    name: "24 Hour Fitness - Fillmore",
    category: "gym",
    subcategory: "Full Gym",
    address: "1200 Van Ness Ave",
    neighborhood: "Nob Hill",
    description: "Super Sport location with pool, basketball court, and sauna. Great value for the amenities.",
    price_tier: 2,
    avg_price: 40,
    tags: ["pool", "basketball", "sauna", "24-7"],
    lat: 37.7870,
    lng: -122.4213,
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "24-fitness-market",
    name: "24 Hour Fitness - Market St",
    category: "gym",
    subcategory: "Full Gym",
    address: "100 14th St",
    neighborhood: "SoMa",
    description: "Convenient Market St location near BART. Solid equipment, busy during peak hours.",
    price_tier: 2,
    avg_price: 35,
    tags: ["near-BART", "cardio", "weights"],
    lat: 37.7678,
    lng: -122.4167,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-02T00:00:00Z",
    updated_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "crunch-fitness-sf",
    name: "Crunch Fitness",
    category: "gym",
    subcategory: "Full Gym",
    address: "61 New Montgomery St",
    neighborhood: "SoMa",
    description: "Budget-friendly full gym with group classes. Base membership starts around $30/month.",
    price_tier: 1,
    avg_price: 30,
    tags: ["budget", "classes", "downtown"],
    lat: 37.7878,
    lng: -122.4013,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-03T00:00:00Z",
    updated_at: "2024-02-03T00:00:00Z",
  },
  {
    id: "sf-rec-gyms",
    name: "SF Rec & Park Centers",
    category: "gym",
    subcategory: "Public Gym",
    address: "Multiple city rec centers",
    neighborhood: "SoMa",
    description: "City-run rec centers with fitness rooms. Free or very low-cost. Check sfrec.org for locations and schedules.",
    price_tier: 1,
    avg_price: 0,
    tags: ["public", "free", "low-cost"],
    lat: 37.7694,
    lng: -122.4262,
    status: "approved",
    vote_count: 41,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-04T00:00:00Z",
    updated_at: "2024-02-04T00:00:00Z",
  },
  {
    id: "outdoor-fitness",
    name: "Marina Green Fitness Court",
    category: "gym",
    subcategory: "Outdoor",
    address: "Marina Blvd & Scott St",
    neighborhood: "Marina",
    description: "Free outdoor fitness court with bodyweight stations, pull-up bars, and bay views. Also try the Lyon Street stairs.",
    price_tier: 1,
    avg_price: 0,
    tags: ["outdoor", "free", "bay-views", "bodyweight"],
    lat: 37.8065,
    lng: -122.4382,
    status: "approved",
    vote_count: 33,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-05T00:00:00Z",
    updated_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "ymca-embarcadero",
    name: "YMCA - Embarcadero",
    category: "gym",
    subcategory: "Full Gym",
    address: "169 Steuart St",
    neighborhood: "SoMa",
    description: "Full gym with pool, courts, and group classes. Sliding-scale pricing available based on income.",
    price_tier: 2,
    avg_price: 45,
    tags: ["pool", "sliding-scale", "classes", "courts"],
    lat: 37.7921,
    lng: -122.3923,
    status: "approved",
    vote_count: 27,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-06T00:00:00Z",
    updated_at: "2024-02-06T00:00:00Z",
  },

  // === COFFEE ===
  {
    id: "philz-coffee",
    name: "Philz Coffee",
    category: "coffee",
    subcategory: "Pour Over",
    address: "3101 24th St",
    neighborhood: "Mission District",
    description: "SF-born coffee legend. Every cup hand-crafted to order. The Tesora and Mint Mojito Iced are iconic. Multiple locations citywide.",
    price_tier: 1,
    avg_price: 5,
    tags: ["SF-born", "pour-over", "custom-blended", "local-icon"],
    lat: 37.7525,
    lng: -122.4180,
    status: "approved",
    vote_count: 72,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "blue-bottle",
    name: "Blue Bottle Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "66 Mint St",
    neighborhood: "SoMa",
    description: "Third-wave coffee pioneer. Minimalist design, meticulous pour-overs, single-origin beans. The Hayes Valley kiosk (315 Linden St) is the iconic original.",
    price_tier: 2,
    avg_price: 6,
    tags: ["third-wave", "minimalist", "single-origin", "design-forward"],
    lat: 37.7822,
    lng: -122.4074,
    status: "approved",
    vote_count: 65,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-11T00:00:00Z",
    updated_at: "2024-02-11T00:00:00Z",
  },
  {
    id: "ritual-coffee",
    name: "Ritual Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "1026 Valencia St",
    neighborhood: "Mission District",
    description: "OG SF third-wave roaster since 2005. Known for light roasts that highlight origin. Direct-trade sourcing with full transparency.",
    price_tier: 2,
    avg_price: 6,
    tags: ["third-wave-OG", "direct-trade", "light-roast", "Mission"],
    lat: 37.7565,
    lng: -122.4213,
    status: "approved",
    vote_count: 48,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-12T00:00:00Z",
    updated_at: "2024-02-12T00:00:00Z",
  },
  {
    id: "sightglass",
    name: "Sightglass Coffee",
    category: "coffee",
    subcategory: "Roastery Cafe",
    address: "270 7th St",
    neighborhood: "SoMa",
    description: "Jaw-dropping two-story warehouse space with visible roasting operation. One of the most photogenic coffee spots in the city.",
    price_tier: 2,
    avg_price: 6,
    tags: ["stunning-space", "roastery", "industrial", "photogenic"],
    lat: 37.7775,
    lng: -122.4065,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-13T00:00:00Z",
    updated_at: "2024-02-13T00:00:00Z",
  },
  {
    id: "equator-coffees",
    name: "Equator Coffees",
    category: "coffee",
    subcategory: "Specialty",
    address: "986 Market St",
    neighborhood: "SoMa",
    description: "Certified B-Corp, LGBTQ-owned. Deeply committed to sustainability and fair trade. Great coffee with real values behind the brand.",
    price_tier: 2,
    avg_price: 6,
    tags: ["B-Corp", "LGBTQ-owned", "sustainability", "direct-trade"],
    lat: 37.7818,
    lng: -122.4105,
    status: "approved",
    vote_count: 42,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "andytown",
    name: "Andytown Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "3655 Lawton St",
    neighborhood: "Outer Sunset",
    description: "Beloved Sunset shop with Irish roots. Famous for the Snowy Plover — espresso with whipped cream and brown sugar. Perfectly cozy for foggy days.",
    price_tier: 2,
    avg_price: 6,
    tags: ["Irish-influenced", "snowy-plover", "cozy", "Sunset-gem"],
    lat: 37.7566,
    lng: -122.4976,
    status: "approved",
    vote_count: 51,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "saint-frank",
    name: "Saint Frank Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "2340 Polk St",
    neighborhood: "Nob Hill",
    description: "Named after San Francisco's patron saint. Meticulous attention to detail, beautiful airy space, and exceptional direct-trade single-origin coffees.",
    price_tier: 2,
    avg_price: 6,
    tags: ["elegant", "precision", "direct-trade", "beautiful-space"],
    lat: 37.7988,
    lng: -122.4218,
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-16T00:00:00Z",
    updated_at: "2024-02-16T00:00:00Z",
  },
  {
    id: "verve-coffee",
    name: "Verve Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "2101 Market St",
    neighborhood: "Castro",
    description: "Santa Cruz-born roaster known for bright, fruit-forward coffees. Clean California-cool aesthetic. Strong farm relationships worldwide.",
    price_tier: 2,
    avg_price: 6,
    tags: ["bright-roasts", "California-cool", "specialty"],
    lat: 37.7679,
    lng: -122.4278,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-17T00:00:00Z",
    updated_at: "2024-02-17T00:00:00Z",
  },
  {
    id: "wrecking-ball",
    name: "Wrecking Ball Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "2271 Union St",
    neighborhood: "Marina",
    description: "Founded by Trish Rothgeb who coined the term 'third wave coffee.' Light roasts that are complex and nuanced. A serious coffee nerd's dream.",
    price_tier: 2,
    avg_price: 6,
    tags: ["woman-owned", "light-roast", "third-wave-coiner"],
    lat: 37.7983,
    lng: -122.4365,
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-18T00:00:00Z",
    updated_at: "2024-02-18T00:00:00Z",
  },

  // === COFFEE: Founder-famous spots (from Starter Guide to SF) ===
  {
    id: "the-mill",
    name: "The Mill",
    category: "coffee",
    subcategory: "Cafe",
    address: "736 Divisadero St",
    neighborhood: "NoPa",
    description: "Famous for $4 toast and great coffee. Long communal table, lots of natural light. A NoPa staple for remote workers and founders.",
    price_tier: 2,
    avg_price: 6,
    tags: ["toast", "communal-table", "founders", "remote-work"],
    lat: 37.7762,
    lng: -122.4382,
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "cafe-reveille",
    name: "Cafe Reveille",
    category: "coffee",
    subcategory: "Cafe",
    address: "610 Long Oak St",
    neighborhood: "Lower Haight",
    description: "Cozy neighborhood cafe with solid wifi. Good mix of locals and remote workers. Great for focused morning work sessions.",
    price_tier: 2,
    avg_price: 6,
    tags: ["cozy", "neighborhood", "wifi", "remote-work"],
    lat: 37.7719,
    lng: -122.4340,
    status: "approved",
    vote_count: 28,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "la-boulangerie",
    name: "La Boulangerie",
    category: "coffee",
    subcategory: "French Bakery Cafe",
    address: "Hayes Valley, SF",
    neighborhood: "Hayes Valley",
    description: "French bakery cafe where you'll run into founders and VCs on any given day. The unofficial meeting spot for Hayes Valley tech people.",
    price_tier: 2,
    avg_price: 7,
    tags: ["french", "founders", "VCs", "meetings", "hayes-valley"],
    lat: 37.7762,
    lng: -122.4230,
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "cafe-shoji",
    name: "Cafe Shoji",
    category: "coffee",
    subcategory: "Japanese Cafe",
    address: "Financial District, SF",
    neighborhood: "Financial District",
    description: "Japanese-inspired cafe in FiDi. Calm, minimal atmosphere perfect for focused work or 1:1 meetings.",
    price_tier: 2,
    avg_price: 6,
    tags: ["japanese", "minimal", "calm", "meetings", "fidi"],
    lat: 37.7900,
    lng: -122.4010,
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "the-buoy",
    name: "The Buoy",
    category: "coffee",
    subcategory: "Cafe",
    address: "Hayes Valley, SF",
    neighborhood: "Hayes Valley",
    description: "Trendy spot in Hayes Valley. Popular with the tech crowd for casual meetings and afternoon pick-me-ups.",
    price_tier: 2,
    avg_price: 6,
    tags: ["trendy", "social", "hayes-valley", "meetings"],
    lat: 37.7755,
    lng: -122.4245,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "flywheel-coffee",
    name: "Flywheel Coffee",
    category: "coffee",
    subcategory: "Cafe",
    address: "672 Stanyan St",
    neighborhood: "Upper Haight",
    description: "Great starting point for Golden Gate Park walking meetings. Cozy, laptop-friendly, and right at the park entrance.",
    price_tier: 1,
    avg_price: 5,
    tags: ["golden-gate-park", "walking-meetings", "cozy", "laptop-friendly"],
    lat: 37.7690,
    lng: -122.4530,
    status: "approved",
    vote_count: 25,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "coffee-movement",
    name: "The Coffee Movement",
    category: "coffee",
    subcategory: "Cafe",
    address: "Richmond, SF",
    neighborhood: "Richmond",
    description: "Community-focused cafe in the Richmond. Less crowded than downtown spots — great for uninterrupted deep work.",
    price_tier: 1,
    avg_price: 5,
    tags: ["community", "quiet", "richmond", "deep-work"],
    lat: 37.7800,
    lng: -122.4650,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "dandelion-chocolate",
    name: "Dandelion Chocolate",
    category: "coffee",
    subcategory: "Chocolate Cafe",
    address: "2600 16th St",
    neighborhood: "Mission District",
    description: "Bean-to-bar chocolate factory with a cafe. Hot chocolate is world-class. A unique meeting spot that'll impress anyone.",
    price_tier: 2,
    avg_price: 7,
    tags: ["chocolate", "unique", "factory", "mission", "impressive"],
    lat: 37.7655,
    lng: -122.4095,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },

  // === STARTUP PROGRAMS ===
  {
    id: "y-combinator",
    name: "Y Combinator",
    category: "startup",
    subcategory: "Accelerator",
    address: "335 Pioneer Way, Mountain View",
    neighborhood: "SoMa",
    description: "The most famous startup accelerator. $500K standard deal. Demo Day is the Super Bowl of startups. Batches run twice a year.",
    price_tier: 1,
    tags: ["accelerator", "top-tier", "seed", "demo-day"],
    lat: 37.7860,
    lng: -122.3990,
    website: "https://www.ycombinator.com",
    status: "approved",
    vote_count: 90,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "south-park-commons",
    name: "South Park Commons",
    category: "startup",
    subcategory: "Community",
    address: "South Park, SF",
    neighborhood: "SoMa",
    description: "Community for technologists exploring what's next. Space to tinker, learn, find co-founders. Alumni have started billion-dollar companies.",
    price_tier: 1,
    tags: ["community", "exploration", "co-founders", "high-caliber"],
    lat: 37.7818,
    lng: -122.3940,
    website: "https://www.southparkcommons.com",
    status: "approved",
    vote_count: 70,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "pear-vc-pearx",
    name: "PearX (Pear VC)",
    category: "startup",
    subcategory: "Accelerator",
    address: "Palo Alto / SF",
    neighborhood: "SoMa",
    description: "Pre-seed/seed accelerator by Pear VC. Focused on technical founders. Strong alumni network and hands-on mentorship.",
    price_tier: 1,
    tags: ["accelerator", "pre-seed", "technical-founders"],
    lat: 37.7835,
    lng: -122.4010,
    website: "https://www.pear.vc",
    status: "approved",
    vote_count: 50,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "hf0-residency",
    name: "HF0 Residency",
    category: "startup",
    subcategory: "Residency",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Hacker residency for technical founders. Live and build with other hackers for a few weeks. Very selective, very intense.",
    price_tier: 1,
    tags: ["residency", "hackers", "intense", "selective"],
    lat: 37.7780,
    lng: -122.3960,
    website: "https://www.hf0.com",
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "a16z-speedrun",
    name: "a16z Speedrun",
    category: "startup",
    subcategory: "Accelerator",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Andreessen Horowitz's accelerator program. Fast-paced, backed by one of the biggest VC firms. Access to a16z's entire network.",
    price_tier: 1,
    tags: ["accelerator", "a16z", "top-tier", "network"],
    lat: 37.7850,
    lng: -122.4030,
    website: "https://speedrun.a16z.com",
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "z-fellows",
    name: "Z Fellows",
    category: "startup",
    subcategory: "Fellowship",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Fast-track into Silicon Valley for ambitious founders under 26. Fellowship with funding and mentorship.",
    price_tier: 1,
    tags: ["fellowship", "young-founders", "under-26", "funding"],
    lat: 37.7870,
    lng: -122.3970,
    website: "https://www.zfellows.com",
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "founder-university",
    name: "Founder University",
    category: "startup",
    subcategory: "Program",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Pre-accelerator program. Great for first-time founders figuring out their idea. Community and structure without the pressure.",
    price_tier: 1,
    tags: ["pre-accelerator", "first-time-founders", "community"],
    lat: 37.7840,
    lng: -122.4060,
    website: "https://www.founderuniversity.com",
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "alchemist-accelerator",
    name: "Alchemist Accelerator",
    category: "startup",
    subcategory: "Accelerator",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Focused on enterprise/B2B startups. Great for founders building for businesses, not consumers. Strong corporate network.",
    price_tier: 1,
    tags: ["accelerator", "enterprise", "B2B", "corporate"],
    lat: 37.7795,
    lng: -122.3930,
    website: "https://alchemistaccelerator.com",
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "launch-accelerator",
    name: "LAUNCH Accelerator",
    category: "startup",
    subcategory: "Accelerator",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Jason Calacanis's accelerator. Broad focus, strong media presence. Good for founders who want visibility.",
    price_tier: 1,
    tags: ["accelerator", "media", "visibility", "broad"],
    lat: 37.7810,
    lng: -122.4000,
    website: "https://www.launchaccelerator.co",
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "berkeley-skydeck",
    name: "Berkeley SkyDeck",
    category: "startup",
    subcategory: "Accelerator",
    address: "UC Berkeley, Berkeley",
    neighborhood: "Other",
    description: "UC Berkeley's startup accelerator. Access to Berkeley's research and talent pipeline. Strong in deep tech and biotech.",
    price_tier: 1,
    tags: ["accelerator", "university", "deep-tech", "biotech"],
    lat: 37.8716,
    lng: -122.2591,
    website: "https://skydeck.berkeley.edu",
    status: "approved",
    vote_count: 28,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "interact-fellowship",
    name: "Interact",
    category: "startup",
    subcategory: "Fellowship",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Fellowship for ambitious technologists. Community of builders across SF. Great for people exploring ideas before committing.",
    price_tier: 1,
    tags: ["fellowship", "community", "exploration", "technologists"],
    lat: 37.7825,
    lng: -122.3985,
    website: "https://joininteract.com",
    status: "approved",
    vote_count: 32,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "pioneer",
    name: "Pioneer",
    category: "startup",
    subcategory: "Program",
    address: "Remote / SF",
    neighborhood: "SoMa",
    description: "Global tournament for ambitious outsiders. Apply with your project, get ranked by the community. Winners get funding and mentorship.",
    price_tier: 1,
    tags: ["global", "tournament", "remote-friendly", "funding"],
    lat: 37.7855,
    lng: -122.4045,
    website: "https://pioneer.app",
    status: "approved",
    vote_count: 25,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "soma-fellows",
    name: "Soma Fellows",
    category: "startup",
    subcategory: "Fellowship",
    address: "SoMa, SF",
    neighborhood: "SoMa",
    description: "Fellowship for young builders in SoMa. Housing + community + mentorship. Good for people just arriving in SF.",
    price_tier: 1,
    tags: ["fellowship", "housing", "young-founders", "soma"],
    lat: 37.7788,
    lng: -122.4015,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "inception-studio",
    name: "Inception Studio",
    category: "startup",
    subcategory: "Studio",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Startup studio that builds companies from scratch. They bring the idea, you bring the execution. Good for operators looking to become founders.",
    price_tier: 1,
    tags: ["studio", "company-building", "operators"],
    lat: 37.7802,
    lng: -122.3955,
    status: "approved",
    vote_count: 20,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "draper-university",
    name: "Draper University",
    category: "startup",
    subcategory: "Program",
    address: "44 E 3rd Ave, San Mateo",
    neighborhood: "Other",
    description: "Tim Draper's entrepreneurship program. Residential program with classes, mentorship, and pitch competitions. Good for aspiring founders.",
    price_tier: 2,
    tags: ["program", "residential", "entrepreneurship", "pitch"],
    lat: 37.5630,
    lng: -122.3255,
    website: "https://draperuniversity.com",
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "greylock-edge",
    name: "Edge (Greylock)",
    category: "startup",
    subcategory: "Program",
    address: "Greylock Partners, SF",
    neighborhood: "SoMa",
    description: "Greylock's program for early-stage founders. Access to one of the most legendary VC firms and their operator network.",
    price_tier: 1,
    tags: ["program", "greylock", "early-stage", "vc-backed"],
    lat: 37.7845,
    lng: -122.3975,
    website: "https://greylock.com",
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "sequoia-arc",
    name: "Sequoia Arc",
    category: "startup",
    subcategory: "Program",
    address: "Sequoia Capital, Menlo Park",
    neighborhood: "Other",
    description: "Sequoia's company building immersion. Extremely selective. If you get in, you're building with the best VC brand in the world.",
    price_tier: 1,
    tags: ["program", "sequoia", "top-tier", "immersion"],
    lat: 37.4530,
    lng: -122.1817,
    website: "https://www.sequoiacap.com/arc",
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "founders-inc",
    name: "Founders, Inc.",
    category: "startup",
    subcategory: "Accelerator",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Accelerator for immigrant and underrepresented founders. Funding, mentorship, and community for founders building in the US.",
    price_tier: 1,
    tags: ["accelerator", "immigrant-founders", "diversity", "community"],
    lat: 37.7815,
    lng: -122.4025,
    website: "https://www.founders.inc",
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "odf",
    name: "On Deck Founders (ODF)",
    category: "startup",
    subcategory: "Fellowship",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "From idea to conviction. Fellowship for people going from 0 to 1. Strong community network of founders globally.",
    price_tier: 1,
    tags: ["fellowship", "0-to-1", "community", "global"],
    lat: 37.7830,
    lng: -122.4050,
    website: "https://www.beondeck.com",
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "conviction-embed",
    name: "Conviction Embed",
    category: "startup",
    subcategory: "Residency",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Conviction Capital's founder residency. Work alongside the Conviction team to build your company from scratch.",
    price_tier: 1,
    tags: ["residency", "conviction", "company-building"],
    lat: 37.7865,
    lng: -122.3950,
    website: "https://www.conviction.com",
    status: "approved",
    vote_count: 20,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "entrepreneurs-first",
    name: "Entrepreneurs First",
    category: "startup",
    subcategory: "Program",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Found, don't follow. EF helps you find a co-founder and build a company from scratch. Great if you're technical but don't have a co-founder yet.",
    price_tier: 1,
    tags: ["co-founder-matching", "pre-idea", "global"],
    lat: 37.7808,
    lng: -122.3980,
    website: "https://www.joinef.com",
    status: "approved",
    vote_count: 28,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "500-global",
    name: "500 Global",
    category: "startup",
    subcategory: "Accelerator",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "One of the most active early-stage VCs. Flagship accelerator program with a global portfolio of 2,800+ companies across 80 countries.",
    price_tier: 1,
    tags: ["accelerator", "global", "diverse", "active"],
    lat: 37.7822,
    lng: -122.4035,
    website: "https://500.co",
    status: "approved",
    vote_count: 32,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "afore-capital-fir",
    name: "Afore Capital FiR",
    category: "startup",
    subcategory: "Residency",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Founder in Residence program by Afore Capital. Pre-seed focused, helps you go from idea to funded startup.",
    price_tier: 1,
    tags: ["residency", "pre-seed", "idea-stage"],
    lat: 37.7838,
    lng: -122.3995,
    website: "https://afore.vc",
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },

  // === VCs ===
  // Presidio cluster
  {
    id: "sequoia-capital",
    name: "Sequoia Capital",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "2800 Sand Hill Rd / Presidio",
    neighborhood: "Presidio",
    description: "Legendary VC behind Apple, Google, Stripe, and more. One of the most sought-after investors in the world.",
    price_tier: 4,
    tags: ["tier-1", "seed-to-growth", "global"],
    lat: 37.7990,
    lng: -122.4570,
    website: "https://www.sequoiacap.com",
    status: "approved",
    vote_count: 90,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "founders-fund",
    name: "Founders Fund",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "Presidio, SF",
    neighborhood: "Presidio",
    description: "Peter Thiel's fund. Backs bold, contrarian bets. Portfolio includes SpaceX, Palantir, Stripe, Anduril.",
    price_tier: 4,
    tags: ["tier-1", "contrarian", "deep-tech"],
    lat: 37.7985,
    lng: -122.4530,
    website: "https://foundersfund.com",
    status: "approved",
    vote_count: 85,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "a16z",
    name: "Andreessen Horowitz (a16z)",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "Presidio, SF",
    neighborhood: "Presidio",
    description: "One of the biggest and most active VC firms. Seed to growth. Strong in crypto, AI, bio, fintech. Massive platform team.",
    price_tier: 4,
    tags: ["tier-1", "platform", "multi-stage", "ai"],
    lat: 37.7995,
    lng: -122.4510,
    website: "https://a16z.com",
    status: "approved",
    vote_count: 88,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "kleiner-perkins",
    name: "Kleiner Perkins",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "Presidio, SF",
    neighborhood: "Presidio",
    description: "Storied VC firm. Early backer of Amazon, Google, Genentech. Now focused on early-stage with strong Fellows program.",
    price_tier: 4,
    tags: ["tier-1", "early-stage", "fellows-program"],
    lat: 37.7980,
    lng: -122.4550,
    website: "https://www.kleinerperkins.com",
    status: "approved",
    vote_count: 75,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "lux-capital",
    name: "Lux Capital",
    category: "vc",
    subcategory: "Deep Tech VC",
    address: "Presidio, SF",
    neighborhood: "Presidio",
    description: "Deep tech and frontier science. Backs companies in AI, robotics, space, biotech. Not your typical SaaS investor.",
    price_tier: 4,
    tags: ["deep-tech", "science", "frontier"],
    lat: 37.7975,
    lng: -122.4540,
    website: "https://luxcapital.com",
    status: "approved",
    vote_count: 60,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  // FiDi / SoMa cluster
  {
    id: "greylock",
    name: "Greylock Partners",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "FiDi, SF",
    neighborhood: "Financial District",
    description: "Legendary early-stage firm. Backed LinkedIn, Facebook, Airbnb, Discord. Strong operator network.",
    price_tier: 4,
    tags: ["tier-1", "early-stage", "consumer", "enterprise"],
    lat: 37.7910,
    lng: -122.3985,
    website: "https://greylock.com",
    status: "approved",
    vote_count: 80,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "first-round",
    name: "First Round Capital",
    category: "vc",
    subcategory: "Seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Best-in-class seed investor. Uber, Square, Notion alumni. Known for First Round Review content and strong community.",
    price_tier: 3,
    tags: ["seed", "community", "content", "operator-friendly"],
    lat: 37.7855,
    lng: -122.4000,
    website: "https://firstround.com",
    status: "approved",
    vote_count: 70,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "general-catalyst",
    name: "General Catalyst",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Multi-stage firm from seed to growth. Stripe, Snap, Airbnb portfolio. Big on responsible innovation.",
    price_tier: 4,
    tags: ["multi-stage", "growth", "responsible-innovation"],
    lat: 37.7865,
    lng: -122.3960,
    website: "https://www.generalcatalyst.com",
    status: "approved",
    vote_count: 65,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "initialized-capital",
    name: "Initialized Capital",
    category: "vc",
    subcategory: "Seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Garry Tan's fund (now YC president). Strong seed-stage focus. Coinbase, Instacart, Cruise in portfolio.",
    price_tier: 3,
    tags: ["seed", "garry-tan", "yc-connected"],
    lat: 37.7840,
    lng: -122.3980,
    website: "https://initialized.com",
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "khosla-ventures",
    name: "Khosla Ventures",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Vinod Khosla's fund. Strong in climate, AI, health, and deep tech. Willing to take big technical bets.",
    price_tier: 4,
    tags: ["climate", "deep-tech", "ai", "health"],
    lat: 37.7870,
    lng: -122.4020,
    website: "https://www.khoslaventures.com",
    status: "approved",
    vote_count: 62,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "hustle-fund",
    name: "Hustle Fund",
    category: "vc",
    subcategory: "Pre-seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Elizabeth Yin's pre-seed fund. Founder-friendly, fast decisions. Great for first-time founders. Active community.",
    price_tier: 2,
    tags: ["pre-seed", "founder-friendly", "fast", "community"],
    lat: 37.7825,
    lng: -122.4010,
    website: "https://www.hustlefund.vc",
    status: "approved",
    vote_count: 50,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "precursor-ventures",
    name: "Precursor Ventures",
    category: "vc",
    subcategory: "Pre-seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Charles Hudson's pre-seed fund. Focused on underrepresented founders. Fast, transparent, founder-first.",
    price_tier: 2,
    tags: ["pre-seed", "diversity", "founder-first"],
    lat: 37.7835,
    lng: -122.3950,
    website: "https://precursorvc.com",
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "true-ventures",
    name: "True Ventures",
    category: "vc",
    subcategory: "Early-stage VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Early-stage firm with a strong community ethos. Backed Fitbit, Peloton, Ring. Known for True University founder support.",
    price_tier: 3,
    tags: ["early-stage", "community", "founder-support"],
    lat: 37.7850,
    lng: -122.3970,
    website: "https://trueventures.com",
    status: "approved",
    vote_count: 48,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "craft-ventures",
    name: "Craft Ventures",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "David Sacks' fund. Strong in SaaS, fintech, crypto. All-In Podcast fame. Thesis-driven investing.",
    price_tier: 3,
    tags: ["saas", "fintech", "crypto", "all-in-podcast"],
    lat: 37.7845,
    lng: -122.4030,
    website: "https://www.craftventures.com",
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "cowboy-ventures",
    name: "Cowboy Ventures",
    category: "vc",
    subcategory: "Seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Aileen Lee's fund (coined 'unicorn'). Seed-stage, thesis-driven. Strong in consumer and enterprise.",
    price_tier: 3,
    tags: ["seed", "unicorn-coiner", "consumer", "enterprise"],
    lat: 37.7830,
    lng: -122.4045,
    website: "https://www.cowboy.vc",
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "susa-ventures",
    name: "Susa Ventures",
    category: "vc",
    subcategory: "Seed VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Data-driven seed fund. Portfolio includes Robinhood, Flexport, Andela. Strong technical diligence.",
    price_tier: 3,
    tags: ["seed", "data-driven", "technical"],
    lat: 37.7820,
    lng: -122.3990,
    website: "https://www.susaventures.com",
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "gv-google-ventures",
    name: "GV (Google Ventures)",
    category: "vc",
    subcategory: "CVC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Google's venture arm. Seed to growth. Portfolio includes Uber, Slack, Stripe. Access to Google's resources.",
    price_tier: 4,
    tags: ["cvc", "google", "multi-stage", "resources"],
    lat: 37.7860,
    lng: -122.3940,
    website: "https://www.gv.com",
    status: "approved",
    vote_count: 65,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "index-ventures",
    name: "Index Ventures",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "SF",
    neighborhood: "Financial District",
    description: "European-origin, now global. Backed Figma, Discord, Notion, Roblox. Strong in developer tools and gaming.",
    price_tier: 4,
    tags: ["global", "developer-tools", "gaming", "multi-stage"],
    lat: 37.7900,
    lng: -122.4005,
    website: "https://www.indexventures.com",
    status: "approved",
    vote_count: 60,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "accel",
    name: "Accel",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "SF",
    neighborhood: "Financial District",
    description: "Global powerhouse. Early Facebook investor. Strong in enterprise, security, and fintech. Very active in SF.",
    price_tier: 4,
    tags: ["tier-1", "global", "enterprise", "fintech"],
    lat: 37.7895,
    lng: -122.4015,
    website: "https://www.accel.com",
    status: "approved",
    vote_count: 70,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "ribbit-capital",
    name: "Ribbit Capital",
    category: "vc",
    subcategory: "Fintech VC",
    address: "SF",
    neighborhood: "SoMa",
    description: "Fintech-focused. Backed Robinhood, Coinbase, Brex, Nubank. The go-to VC for fintech founders.",
    price_tier: 3,
    tags: ["fintech", "crypto", "banking"],
    lat: 37.7815,
    lng: -122.3965,
    website: "https://ribbitcap.com",
    status: "approved",
    vote_count: 50,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },

  // South Bay VCs (Sand Hill Road / Menlo Park / Palo Alto)
  {
    id: "benchmark",
    name: "Benchmark",
    category: "vc",
    subcategory: "Tier 1 VC",
    address: "2965 Woodside Rd, Woodside",
    neighborhood: "Other",
    description: "Equal partnership, no growth fund. Backed eBay, Twitter, Uber, Snap. One of the most disciplined VC firms ever.",
    price_tier: 4,
    tags: ["tier-1", "early-stage", "equal-partnership"],
    lat: 37.4298,
    lng: -122.2539,
    website: "https://www.benchmark.com",
    status: "approved",
    vote_count: 85,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "lightspeed",
    name: "Lightspeed Venture Partners",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "2200 Sand Hill Rd, Menlo Park",
    neighborhood: "Other",
    description: "Global multi-stage firm. Backed Snap, Affirm, Grafana, Mulesoft. Strong in enterprise and consumer.",
    price_tier: 4,
    tags: ["multi-stage", "global", "enterprise", "consumer"],
    lat: 37.4180,
    lng: -122.2050,
    website: "https://lsvp.com",
    status: "approved",
    vote_count: 65,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "redpoint",
    name: "Redpoint Ventures",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "3000 Sand Hill Rd, Menlo Park",
    neighborhood: "Other",
    description: "Early and growth stage. Backed Stripe, Netflix, Twilio, Snowflake. Strong in infrastructure and developer tools.",
    price_tier: 4,
    tags: ["multi-stage", "infrastructure", "developer-tools"],
    lat: 37.4175,
    lng: -122.2065,
    website: "https://www.redpoint.com",
    status: "approved",
    vote_count: 60,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "norwest-vp",
    name: "Norwest Venture Partners",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "525 University Ave, Palo Alto",
    neighborhood: "Other",
    description: "One of the oldest VC firms (since 1961). Multi-stage, strong in enterprise SaaS and healthcare. $14B+ under management.",
    price_tier: 4,
    tags: ["multi-stage", "enterprise", "healthcare", "legacy"],
    lat: 37.4475,
    lng: -122.1598,
    website: "https://www.nvp.com",
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "sapphire-ventures",
    name: "Sapphire Ventures",
    category: "vc",
    subcategory: "Growth VC",
    address: "Palo Alto",
    neighborhood: "Other",
    description: "Growth-stage firm spun out of SAP. $10B+ under management. Strong in enterprise software and B2B.",
    price_tier: 4,
    tags: ["growth", "enterprise", "b2b"],
    lat: 37.4435,
    lng: -122.1615,
    website: "https://sapphireventures.com",
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "menlo-ventures",
    name: "Menlo Ventures",
    category: "vc",
    subcategory: "Multi-stage VC",
    address: "Menlo Park",
    neighborhood: "Other",
    description: "40+ year track record. Backed Uber, Roku, Siri. Now focused on AI, cyber, and enterprise. Runs Menlo Fellowship for founders.",
    price_tier: 4,
    tags: ["multi-stage", "ai", "cyber", "fellowship"],
    lat: 37.4525,
    lng: -122.1825,
    website: "https://www.menlovc.com",
    status: "approved",
    vote_count: 50,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "plug-and-play",
    name: "Plug and Play",
    category: "vc",
    subcategory: "Accelerator / VC",
    address: "440 N Wolfe Rd, Sunnyvale",
    neighborhood: "Other",
    description: "World's largest startup accelerator platform. 60+ verticals. Also invests from pre-seed to Series A. Massive corporate partner network.",
    price_tier: 2,
    tags: ["accelerator", "corporate", "global", "pre-seed"],
    lat: 37.3875,
    lng: -122.0145,
    website: "https://www.plugandplaytechcenter.com",
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "foundation-capital",
    name: "Foundation Capital",
    category: "vc",
    subcategory: "Early-stage VC",
    address: "Palo Alto",
    neighborhood: "Other",
    description: "Early-stage firm since 1995. Backed Netflix, Lending Club, Sunrun. Focus on fintech, climate, and enterprise.",
    price_tier: 3,
    tags: ["early-stage", "fintech", "climate"],
    lat: 37.4450,
    lng: -122.1640,
    website: "https://foundationcap.com",
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "draper-associates",
    name: "Draper Associates",
    category: "vc",
    subcategory: "Seed VC",
    address: "San Mateo",
    neighborhood: "Other",
    description: "Tim Draper's seed fund. Early backer of Tesla, SpaceX, Skype, Baidu. Bold bets on visionary founders.",
    price_tier: 3,
    tags: ["seed", "visionary", "bold-bets"],
    lat: 37.5630,
    lng: -122.3230,
    website: "https://www.draper.vc",
    status: "approved",
    vote_count: 42,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "gradient-ventures",
    name: "Gradient Ventures (Google AI fund)",
    category: "vc",
    subcategory: "AI VC",
    address: "Palo Alto",
    neighborhood: "Other",
    description: "Google's AI-focused venture fund. Early-stage investments in AI/ML startups. Access to Google's AI expertise and cloud credits.",
    price_tier: 3,
    tags: ["ai", "google", "early-stage", "cloud-credits"],
    lat: 37.4420,
    lng: -122.1600,
    website: "https://www.gradient.com",
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },

  // === PENDING (community submissions awaiting approval) ===
  {
    id: "pending-1",
    name: "New Thai Spot on Clement",
    category: "food",
    subcategory: "Thai",
    address: "512 Clement St",
    neighborhood: "Richmond",
    description: "Just opened last month. Amazing pad see ew for $13. Lunch specials under $10. BYOB on weekdays!",
    price_tier: 1,
    avg_price: 13,
    tags: ["new", "thai", "BYOB", "lunch-special"],
    lat: 37.7831,
    lng: -122.4657,
    status: "pending",
    vote_count: 3,
    votes_needed: 5,
    submitted_by: "user_abc123",
    created_at: "2024-03-20T00:00:00Z",
    updated_at: "2024-03-20T00:00:00Z",
  },
  {
    id: "pending-2",
    name: "Planet Fitness - Daly City",
    category: "gym",
    subcategory: "Budget Gym",
    address: "6400 Mission St, Daly City",
    neighborhood: "Other",
    description: "$10/month, 24/7. Basic but gets the job done. Right off BART.",
    price_tier: 1,
    avg_price: 10,
    tags: ["budget", "24-7", "near-BART"],
    lat: 37.7088,
    lng: -122.4528,
    status: "pending",
    vote_count: 2,
    votes_needed: 5,
    submitted_by: "user_def456",
    created_at: "2024-03-22T00:00:00Z",
    updated_at: "2024-03-22T00:00:00Z",
  },
  {
    id: "pending-3",
    name: "Sunset Produce Market",
    category: "grocery",
    subcategory: "Produce",
    address: "2226 Taraval St",
    neighborhood: "Sunset",
    description: "Incredible cheap produce. Way cheaper than Whole Foods. Family owned, been here for decades.",
    price_tier: 1,
    avg_price: 20,
    tags: ["produce", "family-owned", "cheap"],
    lat: 37.7432,
    lng: -122.4853,
    status: "pending",
    vote_count: 4,
    votes_needed: 5,
    submitted_by: "user_ghi789",
    created_at: "2024-03-25T00:00:00Z",
    updated_at: "2024-03-25T00:00:00Z",
  },

  // === WORKSPACES ===
  {
    id: "founders-cafe",
    name: "Founders Cafe",
    category: "workspace",
    subcategory: "Free Coworking",
    address: "SoMa, SF",
    neighborhood: "SoMa",
    description: "Free coworking for founders and builders. Community-driven space — great for networking and getting work done.",
    price_tier: 1,
    tags: ["free", "coworking", "founders", "community"],
    lat: 37.7785,
    lng: -122.3950,
    website: "https://x.com/founders_cafe",
    status: "approved",
    vote_count: 50,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "mechanics-institute",
    name: "Mechanics' Institute",
    category: "workspace",
    subcategory: "Library & Coworking",
    address: "57 Post St",
    neighborhood: "Financial District",
    description: "Historic library and chess room since 1854. Beautiful reading rooms, fast wifi. $120/year membership is a steal.",
    price_tier: 1,
    avg_price: 10,
    tags: ["library", "historic", "chess", "quiet"],
    lat: 37.7889,
    lng: -122.4030,
    website: "https://www.milibrary.org",
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "sf-main-library",
    name: "SF Main Library",
    category: "workspace",
    subcategory: "Public Library",
    address: "100 Larkin St",
    neighborhood: "Civic Center",
    description: "Free wifi, study rooms, city views from the top floor. The flagship SF public library.",
    price_tier: 1,
    tags: ["free", "library", "study-rooms", "views"],
    lat: 37.7785,
    lng: -122.4156,
    website: "https://sfpl.org",
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "startup-hq",
    name: "StartupHQ",
    category: "workspace",
    subcategory: "Coworking",
    address: "Financial District",
    neighborhood: "Financial District",
    description: "Founder-focused coworking space in the heart of FiDi. 24/7 member access.",
    price_tier: 2,
    avg_price: 200,
    tags: ["coworking", "24-7", "founders"],
    lat: 37.7905,
    lng: -122.4005,
    website: "https://www.startuphq.com",
    status: "approved",
    vote_count: 28,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "neon-coworking",
    name: "NEON",
    category: "workspace",
    subcategory: "Coworking",
    address: "Marina, SF",
    neighborhood: "Marina",
    description: "Neighborhood coworking and event space. Great mix of remote workers, freelancers, and small teams.",
    price_tier: 2,
    avg_price: 250,
    tags: ["coworking", "events", "marina"],
    lat: 37.8005,
    lng: -122.4370,
    website: "https://www.neon.co",
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "homebrew-club",
    name: "Homebrew Club",
    category: "workspace",
    subcategory: "Hacker Space",
    address: "SoMa, SF",
    neighborhood: "SoMa",
    description: "24/7 member-run DIY community space. Web3, AI, and frontier tech experimentation.",
    price_tier: 1,
    tags: ["hacker-space", "24-7", "ai", "web3"],
    lat: 37.7815,
    lng: -122.3985,
    status: "approved",
    vote_count: 20,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "hotel-kabuki-lobby",
    name: "Hotel Kabuki Lobby",
    category: "workspace",
    subcategory: "Hotel Lobby",
    address: "1625 Post St",
    neighborhood: "Japantown",
    description: "Calm, Japanese-inspired hotel lobby. Comfortable seating, peaceful courtyard. Buy a drink and work all day.",
    price_tier: 1,
    tags: ["free", "hotel-lobby", "quiet", "japanese"],
    lat: 37.7854,
    lng: -122.4290,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "proper-hotel-lobby",
    name: "Proper Hotel Lobby",
    category: "workspace",
    subcategory: "Hotel Lobby",
    address: "1100 Market St",
    neighborhood: "Mid-Market",
    description: "Beautifully designed lobby lounge with a cafe. Popular with tech workers for meetings.",
    price_tier: 1,
    tags: ["free", "hotel-lobby", "design", "meetings"],
    lat: 37.7784,
    lng: -122.4128,
    status: "approved",
    vote_count: 15,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "mission-branch-library",
    name: "Mission Branch Library",
    category: "workspace",
    subcategory: "Public Library",
    address: "300 Bartlett St",
    neighborhood: "Mission District",
    description: "Neighborhood branch with solid wifi. Less crowded than Main Library, great for focused work.",
    price_tier: 1,
    tags: ["free", "library", "quiet", "mission"],
    lat: 37.7531,
    lng: -122.4192,
    status: "approved",
    vote_count: 14,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "noe-valley-library",
    name: "Noe Valley Branch Library",
    category: "workspace",
    subcategory: "Public Library",
    address: "451 Jersey St",
    neighborhood: "Noe Valley",
    description: "Bright, modern branch in a family-friendly neighborhood. Great for focused afternoon work.",
    price_tier: 1,
    tags: ["free", "library", "modern", "sunny"],
    lat: 37.7490,
    lng: -122.4340,
    status: "approved",
    vote_count: 12,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },

  // === HOUSING ===
  {
    id: "hacknsleep",
    name: "HackNSleep",
    category: "housing",
    subcategory: "Co-living",
    address: "SoMa, SF",
    neighborhood: "SoMa",
    description: "Cheapest co-living in central SF. Private rooms for hackers, devs, and early-stage founders. Bare-bones but functional.",
    price_tier: 1,
    avg_price: "$1,000-1,800/mo",
    website: "https://hacknsleep.com/",
    tags: ["co-living", "budget", "hackers", "furnished"],
    lat: 37.7790,
    lng: -122.3990,
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "tribe-coliving",
    name: "Tribe Coliving",
    category: "housing",
    subcategory: "Co-living",
    address: "Multiple SF locations",
    neighborhood: "Haight-Ashbury",
    description: "Community-focused co-living with curated housemates. Furnished rooms, cleaning, and utilities included.",
    price_tier: 2,
    avg_price: "$1,300-2,000/mo",
    website: "https://www.tribecoliving.com/",
    tags: ["co-living", "community", "furnished", "utilities-included"],
    lat: 37.7694,
    lng: -122.4462,
    status: "approved",
    vote_count: 25,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "brownstone-housing",
    name: "Brownstone Shared Housing",
    category: "housing",
    subcategory: "Co-living",
    address: "Multiple SF locations",
    neighborhood: "SoMa",
    description: "Professionally managed shared houses across SF. Furnished rooms, straightforward pricing. No startup culture overlay — just solid shared housing.",
    price_tier: 2,
    website: "https://brownstone.live/",
    avg_price: "$1,200-2,200/mo",
    tags: ["co-living", "furnished", "professional"],
    lat: 37.7760,
    lng: -122.4050,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "vybe-living",
    name: "Vybe Living",
    category: "housing",
    subcategory: "Co-living",
    address: "Multiple SF locations",
    neighborhood: "Mission District",
    description: "Established co-living operator. Private furnished rooms, shared kitchen/bath, all utilities and wifi included. Simple all-in pricing.",
    price_tier: 2,
    website: "https://www.vybeliving.com/",
    avg_price: "$1,400-2,500/mo",
    tags: ["co-living", "furnished", "all-inclusive"],
    lat: 37.7599,
    lng: -122.4148,
    status: "approved",
    vote_count: 20,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "the-residency",
    name: "The Residency",
    category: "housing",
    subcategory: "Founder Co-living",
    address: "Mission District, SF",
    neighborhood: "Mission District",
    description: "Co-living for entrepreneurs and creatives. Furnished rooms, shared spaces, and community events. Built-in founder network.",
    price_tier: 2,
    website: "https://www.livetheresidency.com/",
    avg_price: "$1,200-2,200/mo",
    tags: ["co-living", "founders", "community", "events"],
    lat: 37.7580,
    lng: -122.4190,
    status: "approved",
    vote_count: 28,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "agi-house",
    name: "AGI House",
    category: "housing",
    subcategory: "Founder Co-living",
    address: "Pacific Heights, SF",
    neighborhood: "Pacific Heights",
    description: "Invite-only community house for AI researchers and founders. Value comes from the network, not the rent.",
    price_tier: 3,
    website: "https://agihouse.ai/",
    avg_price: "$1,500-3,000/mo",
    tags: ["co-living", "ai", "founders", "invite-only"],
    lat: 37.7925,
    lng: -122.4382,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "the-panoramic",
    name: "The Panoramic",
    category: "housing",
    subcategory: "Micro-Apartments",
    address: "1321 Mission St",
    neighborhood: "SoMa",
    description: "Micro-unit building with studios from ~160 sq ft. Cheapest solo apartments in central SF. Small but efficient.",
    price_tier: 2,
    avg_price: "$1,500-2,000/mo",
    tags: ["micro-unit", "studio", "solo", "central"],
    lat: 37.7756,
    lng: -122.4147,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "mission-dolores-manor",
    name: "Mission Dolores Manor",
    category: "housing",
    subcategory: "Co-living",
    address: "Mission Dolores, SF",
    neighborhood: "Mission District",
    description: "Shared living in one of SF's most walkable, restaurant-rich neighborhoods. Fraction of solo apartment cost.",
    price_tier: 2,
    website: "https://missiondoloresmanor.com/",
    avg_price: "$1,300-2,000/mo",
    tags: ["co-living", "walkable", "mission"],
    lat: 37.7611,
    lng: -122.4268,
    status: "approved",
    vote_count: 15,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "turing-house",
    name: "Turing House",
    category: "housing",
    subcategory: "Founder Co-living",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Community house for AI/ML engineers and researchers. Named after Alan Turing. Networking and shared living.",
    price_tier: 2,
    website: "https://turingsf.com/",
    avg_price: "$1,500-2,500/mo",
    tags: ["co-living", "ai", "ml", "researchers"],
    lat: 37.7830,
    lng: -122.3920,
    status: "approved",
    vote_count: 16,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "arcadia-house",
    name: "Arcadia",
    category: "housing",
    subcategory: "Co-living",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Community house with intellectually engaged housemates. Below-market rents through shared living.",
    price_tier: 2,
    website: "https://joinarcadia.org/",
    avg_price: "$1,200-2,000/mo",
    tags: ["co-living", "community", "intellectual"],
    lat: 37.7770,
    lng: -122.4010,
    status: "approved",
    vote_count: 14,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "hive-coliving",
    name: "Hive Coliving",
    category: "housing",
    subcategory: "Co-living",
    address: "1040 Folsom St",
    neighborhood: "SoMa",
    description: "All-inclusive co-living in a 12,000 sq ft space. 50 bedrooms, furnished with smart TVs, gym, co-working space, and regular community events. Utilities, wifi, and cleaning included.",
    price_tier: 2,
    avg_price: "$1,400-2,200/mo",
    tags: ["co-living", "furnished", "all-inclusive", "gym", "coworking", "community"],
    lat: 37.7762,
    lng: -122.4058,
    website: "https://www.hivecolivingsf.com",
    status: "approved",
    vote_count: 20,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "mission-control-hh",
    name: "Mission Control Hacker House",
    category: "housing",
    subcategory: "Hacker House",
    address: "Mission District, SF",
    neighborhood: "Mission District",
    description: "Hacker house for builders and founders in the Mission. Live and build alongside other ambitious people shipping real products.",
    price_tier: 2,
    website: "https://x.com/mission__ctrl",
    avg_price: "$1,500-2,500/mo",
    tags: ["hacker-house", "founders", "builders", "mission"],
    lat: 37.7590,
    lng: -122.4220,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "atmosphere-house",
    name: "Atmosphere Hacker House",
    category: "housing",
    subcategory: "Hacker House",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Hacker house for tech builders. Community-driven living with other engineers and founders working on hard problems.",
    price_tier: 2,
    website: "https://x.com/houseAtmosphere",
    avg_price: "$1,500-2,500/mo",
    tags: ["hacker-house", "tech", "community"],
    lat: 37.7810,
    lng: -122.3960,
    status: "approved",
    vote_count: 16,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "hsr-hacker-house",
    name: "HSR Hacker House",
    category: "housing",
    subcategory: "Hacker House",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Hacker house focused on shipping fast. Short and long-term stays for developers and founders building startups.",
    price_tier: 2,
    website: "https://x.com/hsrhackerhouse",
    avg_price: "$1,200-2,000/mo",
    tags: ["hacker-house", "short-term", "startups"],
    lat: 37.7800,
    lng: -122.4020,
    status: "approved",
    vote_count: 14,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "gomry-house",
    name: "Gomry Hacker House",
    category: "housing",
    subcategory: "Hacker House",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Founder-oriented community house. Live with other early-stage founders building companies in SF.",
    price_tier: 2,
    website: "https://www.gomry.com/",
    avg_price: "$1,500-2,500/mo",
    tags: ["hacker-house", "founders", "early-stage"],
    lat: 37.7775,
    lng: -122.3945,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "solo-founders-program",
    name: "Solo Founders Program",
    category: "housing",
    subcategory: "Founder Co-living",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Co-living program designed for solo founders. Live with other people building companies alone — shared accountability, lower rent, built-in community.",
    price_tier: 2,
    website: "https://www.sfp.club/",
    avg_price: "$1,500-2,500/mo",
    tags: ["co-living", "founders", "solo-founders", "community"],
    lat: 37.7815,
    lng: -122.3980,
    status: "approved",
    vote_count: 15,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "accelr8",
    name: "ACCELR8",
    category: "housing",
    subcategory: "Founder Co-living",
    address: "San Francisco",
    neighborhood: "SoMa",
    description: "Co-living and accelerator hybrid for early-stage founders. Live with other builders, get mentorship, and ship faster.",
    price_tier: 2,
    website: "https://joinaccelr8.com/",
    avg_price: "$1,500-2,500/mo",
    tags: ["co-living", "founders", "accelerator", "mentorship"],
    lat: 37.7800,
    lng: -122.4010,
    status: "approved",
    vote_count: 15,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "linkedlivin",
    name: "LinkedLivin",
    category: "housing",
    subcategory: "Co-living",
    address: "Multiple SF locations",
    neighborhood: "SoMa",
    description: "Professional-focused co-living that connects you with roommates in your industry. LinkedIn meets apartment sharing.",
    price_tier: 2,
    website: "https://www.linkedlivin.com/",
    avg_price: "$1,400-2,200/mo",
    tags: ["co-living", "professionals", "roommate-matching"],
    lat: 37.7830,
    lng: -122.3920,
    status: "approved",
    vote_count: 15,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
];
