import { Place } from "./types";

// All 51 venues from HydraDB — serves as local fallback + browse data
export const SAMPLE_PLACES: Place[] = [
  // === FOOD: Mexican ===
  {
    id: "la-taqueria",
    name: "La Taqueria",
    category: "food",
    subcategory: "Mexican",
    address: "2889 Mission St",
    neighborhood: "Mission District",
    description: "Legendary SF burrito, James Beard winner. Cash only, no rice in the burrito — just meat, beans, and perfection.",
    price_tier: 1,
    avg_price: 11,
    tags: ["cash-only", "local-icon", "burritos"],
    lat: 37.7509,
    lng: -122.4181,
    status: "approved",
    vote_count: 87,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "el-farolito",
    name: "El Farolito",
    category: "food",
    subcategory: "Mexican",
    address: "2779 Mission St",
    neighborhood: "Mission District",
    description: "Giant super burritos, open late. The go-to spot for a 2am burrito that'll last you two meals.",
    price_tier: 1,
    avg_price: 11,
    tags: ["late-night", "burritos", "local-icon"],
    lat: 37.7525,
    lng: -122.4183,
    status: "approved",
    vote_count: 72,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "taqueria-cancun",
    name: "Taqueria Cancun",
    category: "food",
    subcategory: "Mexican",
    address: "2288 Mission St",
    neighborhood: "Mission District",
    description: "Huge burritos under $11. Fast service, generous portions, and great salsa bar.",
    price_tier: 1,
    avg_price: 10,
    tags: ["burritos", "fast-service"],
    lat: 37.7583,
    lng: -122.4191,
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-12T00:00:00Z",
    updated_at: "2024-01-12T00:00:00Z",
  },
  {
    id: "taqueria-el-buen-sabor",
    name: "Taqueria El Buen Sabor",
    category: "food",
    subcategory: "Mexican",
    address: "699 Valencia St",
    neighborhood: "Mission District",
    description: "Under $10 burritos, authentic flavors. A neighborhood staple that never disappoints.",
    price_tier: 1,
    avg_price: 9,
    tags: ["burritos", "authentic"],
    lat: 37.7604,
    lng: -122.4216,
    status: "approved",
    vote_count: 33,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-14T00:00:00Z",
    updated_at: "2024-01-14T00:00:00Z",
  },

  // === FOOD: Mediterranean ===
  {
    id: "truly-mediterranean",
    name: "Truly Mediterranean",
    category: "food",
    subcategory: "Mediterranean",
    address: "3109 16th St",
    neighborhood: "Mission District",
    description: "Best falafel in the city under $10. BYOB friendly. The lamb shawarma is a must.",
    price_tier: 1,
    avg_price: 9,
    tags: ["falafel", "BYOB"],
    lat: 37.7649,
    lng: -122.4194,
    status: "approved",
    vote_count: 58,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "old-jerusalem",
    name: "Old Jerusalem",
    category: "food",
    subcategory: "Mediterranean",
    address: "2976 Mission St",
    neighborhood: "Mission District",
    description: "Authentic Middle Eastern, huge portions. Family-run with homemade everything.",
    price_tier: 1,
    avg_price: 12,
    tags: ["middle-eastern", "family-run"],
    lat: 37.7530,
    lng: -122.4180,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-16T00:00:00Z",
    updated_at: "2024-01-16T00:00:00Z",
  },
  {
    id: "sunrise-deli",
    name: "Sunrise Deli",
    category: "food",
    subcategory: "Mediterranean",
    address: "2115 Irving St",
    neighborhood: "Sunset",
    description: "Massive shawarma plates that feed two. Hidden gem in the Sunset.",
    price_tier: 1,
    avg_price: 11,
    tags: ["shawarma", "neighborhood-gem"],
    lat: 37.7637,
    lng: -122.4680,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-17T00:00:00Z",
    updated_at: "2024-01-17T00:00:00Z",
  },

  // === FOOD: Vietnamese ===
  {
    id: "saigon-sandwich",
    name: "Saigon Sandwich",
    category: "food",
    subcategory: "Vietnamese",
    address: "560 Larkin St",
    neighborhood: "Tenderloin",
    description: "Best banh mi in SF, legendary $5. Cash only, always a line, always worth it.",
    price_tier: 1,
    avg_price: 5,
    tags: ["cash-only", "local-icon", "banh-mi"],
    lat: 37.7833,
    lng: -122.4170,
    status: "approved",
    vote_count: 94,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "turtle-tower",
    name: "Turtle Tower",
    category: "food",
    subcategory: "Vietnamese",
    address: "645 Larkin St",
    neighborhood: "Tenderloin",
    description: "Authentic Northern Vietnamese pho. Clean, clear broth — the real thing.",
    price_tier: 1,
    avg_price: 13,
    tags: ["pho", "authentic"],
    lat: 37.7843,
    lng: -122.4166,
    status: "approved",
    vote_count: 41,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-18T00:00:00Z",
    updated_at: "2024-01-18T00:00:00Z",
  },
  {
    id: "pho-2000",
    name: "Pho 2000",
    category: "food",
    subcategory: "Vietnamese",
    address: "637 Larkin St",
    neighborhood: "Tenderloin",
    description: "Generous pho bowls at great prices. Quick service, solid flavors.",
    price_tier: 1,
    avg_price: 12,
    tags: ["pho", "quick-service"],
    lat: 37.7840,
    lng: -122.4167,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-19T00:00:00Z",
    updated_at: "2024-01-19T00:00:00Z",
  },
  {
    id: "hai-ky-mi-gia",
    name: "Hai Ky Mi Gia",
    category: "food",
    subcategory: "Vietnamese",
    address: "707 Ellis St",
    neighborhood: "Tenderloin",
    description: "Dry egg noodles, authentic Vietnamese-Chinese. A hidden gem for noodle lovers.",
    price_tier: 1,
    avg_price: 10,
    tags: ["noodles", "authentic"],
    lat: 37.7830,
    lng: -122.4152,
    status: "approved",
    vote_count: 18,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "bun-mee",
    name: "Bun Mee",
    category: "food",
    subcategory: "Vietnamese",
    address: "674 Geary St",
    neighborhood: "Tenderloin",
    description: "Modern banh mi, great combos. A step up from the classic with fun twists.",
    price_tier: 1,
    avg_price: 10,
    tags: ["banh-mi", "modern"],
    lat: 37.7862,
    lng: -122.4138,
    status: "approved",
    vote_count: 25,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-21T00:00:00Z",
    updated_at: "2024-01-21T00:00:00Z",
  },

  // === FOOD: Chinese ===
  {
    id: "good-mong-kok",
    name: "Good Mong Kok",
    category: "food",
    subcategory: "Chinese",
    address: "1039 Stockton St",
    neighborhood: "Chinatown",
    description: "Dim sum to-go, $3-5 boxes. Cash only, grab and go — perfect cheap breakfast.",
    price_tier: 1,
    avg_price: 4,
    tags: ["dim-sum", "cash-only", "bakery"],
    lat: 37.7948,
    lng: -122.4093,
    status: "approved",
    vote_count: 63,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-11T00:00:00Z",
    updated_at: "2024-01-11T00:00:00Z",
  },
  {
    id: "yin-du-wonton",
    name: "Yin Du Wonton",
    category: "food",
    subcategory: "Chinese",
    address: "731 Vallejo St",
    neighborhood: "Chinatown",
    description: "Hand-pulled noodles and wontons. Incredible textures at unbeatable prices.",
    price_tier: 1,
    avg_price: 9,
    tags: ["noodles", "wonton"],
    lat: 37.7979,
    lng: -122.4092,
    status: "approved",
    vote_count: 27,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-22T00:00:00Z",
    updated_at: "2024-01-22T00:00:00Z",
  },
  {
    id: "san-tung",
    name: "San Tung",
    category: "food",
    subcategory: "Chinese",
    address: "1031 Irving St",
    neighborhood: "Inner Sunset",
    description: "Famous dry-fried chicken wings that are worth the wait. Noodle dishes are solid too.",
    price_tier: 1,
    avg_price: 12,
    tags: ["dry-fried-chicken-wings", "noodles"],
    lat: 37.7637,
    lng: -122.4694,
    status: "approved",
    vote_count: 51,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-18T00:00:00Z",
    updated_at: "2024-01-18T00:00:00Z",
  },
  {
    id: "aa-bakery",
    name: "AA Bakery & Cafe",
    category: "food",
    subcategory: "Chinese",
    address: "1068 Stockton St",
    neighborhood: "Chinatown",
    description: "Egg tarts $1.50, pork buns $2, no frills. The best cheap snack in Chinatown.",
    price_tier: 1,
    avg_price: 3,
    tags: ["bakery", "egg-tarts", "bbq-pork-buns"],
    lat: 37.7953,
    lng: -122.4094,
    status: "approved",
    vote_count: 44,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-23T00:00:00Z",
    updated_at: "2024-01-23T00:00:00Z",
  },
  {
    id: "delicious-dim-sum",
    name: "Delicious Dim Sum",
    category: "food",
    subcategory: "Chinese",
    address: "752 Jackson St",
    neighborhood: "Chinatown",
    description: "Pork buns & shrimp dumplings $3-6, always a line. Worth every minute of the wait.",
    price_tier: 1,
    avg_price: 5,
    tags: ["dim-sum", "to-go", "cash-only"],
    lat: 37.7963,
    lng: -122.4074,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-25T00:00:00Z",
    updated_at: "2024-01-25T00:00:00Z",
  },
  {
    id: "house-of-pancakes",
    name: "House of Pancakes",
    category: "food",
    subcategory: "Chinese",
    address: "635 Jackson St",
    neighborhood: "Chinatown",
    description: "Scallion pancakes $4, pot stickers $6. Simple, cheap, and absolutely delicious.",
    price_tier: 1,
    avg_price: 6,
    tags: ["scallion-pancakes", "dumplings", "cash-only"],
    lat: 37.7959,
    lng: -122.4065,
    status: "approved",
    vote_count: 31,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-26T00:00:00Z",
    updated_at: "2024-01-26T00:00:00Z",
  },
  {
    id: "kingdom-of-dumpling",
    name: "Kingdom of Dumpling",
    category: "food",
    subcategory: "Chinese",
    address: "1713 Taraval St",
    neighborhood: "Sunset",
    description: "XLB and dumplings, Sunset favorite. The soup dumplings rival places twice the price.",
    price_tier: 1,
    avg_price: 10,
    tags: ["dumplings", "XLB"],
    lat: 37.7432,
    lng: -122.4831,
    status: "approved",
    vote_count: 39,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-27T00:00:00Z",
    updated_at: "2024-01-27T00:00:00Z",
  },

  // === FOOD: Other cuisines ===
  {
    id: "senor-sisig",
    name: "Senor Sisig",
    category: "food",
    subcategory: "Filipino",
    address: "Food trucks citywide",
    neighborhood: "SoMa",
    description: "Filipino fusion bowls and burritos. Unique SF flavor you can't get anywhere else.",
    price_tier: 1,
    avg_price: 11,
    tags: ["food-truck", "bowls", "fusion"],
    lat: 37.7620,
    lng: -122.4200,
    status: "approved",
    vote_count: 48,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-28T00:00:00Z",
    updated_at: "2024-01-28T00:00:00Z",
  },
  {
    id: "mandalay-restaurant",
    name: "Mandalay Restaurant",
    category: "food",
    subcategory: "Burmese",
    address: "4348 California St",
    neighborhood: "Richmond",
    description: "Tea leaf salad $10, unique Burmese food. One of the few Burmese restaurants in the city.",
    price_tier: 1,
    avg_price: 12,
    tags: ["burmese", "tea-leaf-salad"],
    lat: 37.7858,
    lng: -122.4629,
    status: "approved",
    vote_count: 26,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "pakwan",
    name: "Pakwan",
    category: "food",
    subcategory: "Indian/Pakistani",
    address: "3182 16th St",
    neighborhood: "Mission District",
    description: "Massive biryani plates under $12, BYOB. Pakistani comfort food at its best.",
    price_tier: 1,
    avg_price: 10,
    tags: ["pakistani", "biryani", "naan", "BYOB"],
    lat: 37.7651,
    lng: -122.4234,
    status: "approved",
    vote_count: 42,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-02T00:00:00Z",
    updated_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "udupi-palace",
    name: "Udupi Palace",
    category: "food",
    subcategory: "Indian",
    address: "1007 Valencia St",
    neighborhood: "Mission District",
    description: "Giant dosas $10-12, all vegetarian. South Indian heaven for veggie lovers.",
    price_tier: 1,
    avg_price: 11,
    tags: ["south-indian", "dosa", "vegetarian"],
    lat: 37.7561,
    lng: -122.4210,
    status: "approved",
    vote_count: 36,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-03T00:00:00Z",
    updated_at: "2024-02-03T00:00:00Z",
  },
  {
    id: "naan-n-curry",
    name: "Naan N Curry",
    category: "food",
    subcategory: "Indian",
    address: "336 O'Farrell St",
    neighborhood: "Tenderloin",
    description: "Cheap curry and naan, open super late. The late-night Indian spot everyone ends up at.",
    price_tier: 1,
    avg_price: 10,
    tags: ["late-night", "naan", "curry"],
    lat: 37.7860,
    lng: -122.4107,
    status: "approved",
    vote_count: 37,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-04T00:00:00Z",
    updated_at: "2024-02-04T00:00:00Z",
  },
  {
    id: "lers-ros",
    name: "Lers Ros Thai",
    category: "food",
    subcategory: "Thai",
    address: "730 Larkin St",
    neighborhood: "Tenderloin",
    description: "Best authentic Thai in SF, big portions. They don't tone down the spice.",
    price_tier: 1,
    avg_price: 12,
    tags: ["thai", "spicy", "authentic"],
    lat: 37.7831,
    lng: -122.4175,
    status: "approved",
    vote_count: 53,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-05T00:00:00Z",
    updated_at: "2024-02-05T00:00:00Z",
  },

  // === FOOD: Pizza ===
  {
    id: "costco-pizza",
    name: "Costco Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "450 10th St",
    neighborhood: "SoMa",
    description: "$1.99 slice, $9.95 whole pizza. You don't even need a membership for the food court.",
    price_tier: 1,
    avg_price: 2,
    tags: ["bulk", "value"],
    lat: 37.7700,
    lng: -122.4050,
    status: "approved",
    vote_count: 73,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "arinell-pizza",
    name: "Arinell Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "509 Valencia St",
    neighborhood: "Mission District",
    description: "Legit NY-style slices, $4-5 a slice. Thin crust done right.",
    price_tier: 1,
    avg_price: 5,
    tags: ["NY-style", "cash-friendly"],
    lat: 37.7621,
    lng: -122.4220,
    status: "approved",
    vote_count: 40,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-08T00:00:00Z",
    updated_at: "2024-02-08T00:00:00Z",
  },
  {
    id: "golden-boy-pizza",
    name: "Golden Boy Pizza",
    category: "food",
    subcategory: "Pizza",
    address: "542 Green St",
    neighborhood: "North Beach",
    description: "Thick focaccia-style, legendary late night. The clam & garlic slice is iconic.",
    price_tier: 1,
    avg_price: 5,
    tags: ["focaccia-style", "local-icon", "late-night"],
    lat: 37.7997,
    lng: -122.4074,
    status: "approved",
    vote_count: 66,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-09T00:00:00Z",
    updated_at: "2024-02-09T00:00:00Z",
  },

  // === FOOD: Other ===
  {
    id: "grubstake",
    name: "Grubstake",
    category: "food",
    subcategory: "Late Night",
    address: "1525 Pine St",
    neighborhood: "Nob Hill",
    description: "Late-night burgers in a converted train car. Portuguese specialties and classic diner vibes.",
    price_tier: 1,
    avg_price: 12,
    tags: ["late-night", "portuguese", "burgers"],
    lat: 37.7887,
    lng: -122.4207,
    status: "approved",
    vote_count: 34,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "ikes-sandwiches",
    name: "Ike's Love & Sandwiches",
    category: "food",
    subcategory: "Sandwiches",
    address: "Multiple SF locations",
    neighborhood: "SoMa",
    description: "Dutch crunch sandwiches, massive portions. The dirty sauce is legendary.",
    price_tier: 1,
    avg_price: 12,
    tags: ["sandwiches", "dutch-crunch", "local"],
    lat: 37.7749,
    lng: -122.4194,
    status: "approved",
    vote_count: 43,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-11T00:00:00Z",
    updated_at: "2024-02-11T00:00:00Z",
  },

  // === GROCERY ===
  {
    id: "grocery-outlet",
    name: "Grocery Outlet",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "Mission District",
    description: "40-60% off retail, name brands. Selection changes weekly — treasure hunt shopping.",
    price_tier: 1,
    avg_price: 30,
    tags: ["bargain", "treasure-hunt"],
    lat: 37.7700,
    lng: -122.4250,
    status: "approved",
    vote_count: 56,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "costco-sf",
    name: "Costco",
    category: "grocery",
    subcategory: "Warehouse",
    address: "450 10th St",
    neighborhood: "SoMa",
    description: "In-city Costco, bulk everything + $5 rotisserie chicken. Membership pays for itself.",
    price_tier: 1,
    avg_price: 50,
    tags: ["bulk", "membership"],
    lat: 37.7700,
    lng: -122.4050,
    status: "approved",
    vote_count: 68,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "smart-and-final",
    name: "Smart & Final",
    category: "grocery",
    subcategory: "Supermarket",
    address: "1245 South Van Ness",
    neighborhood: "Mission District",
    description: "Bulk pricing, no membership needed. Great for stocking up without a Costco card.",
    price_tier: 1,
    avg_price: 40,
    tags: ["bulk", "no-membership"],
    lat: 37.7565,
    lng: -122.4165,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-13T00:00:00Z",
    updated_at: "2024-02-13T00:00:00Z",
  },
  {
    id: "duc-loi",
    name: "Duc Loi Supermarket",
    category: "grocery",
    subcategory: "Asian Grocery",
    address: "2200 Mission St",
    neighborhood: "Mission District",
    description: "Amazing produce prices. Best Asian grocery selection in the Mission.",
    price_tier: 1,
    avg_price: 25,
    tags: ["asian-produce", "fresh"],
    lat: 37.7583,
    lng: -122.4191,
    status: "approved",
    vote_count: 37,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "trader-joes",
    name: "Trader Joe's",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "North Beach",
    description: "Great private-label products, good prices. Wine section is unbeatable value.",
    price_tier: 1,
    avg_price: 40,
    tags: ["value", "private-label", "wine"],
    lat: 37.8059,
    lng: -122.4148,
    status: "approved",
    vote_count: 62,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "safeway",
    name: "Safeway",
    category: "grocery",
    subcategory: "Supermarket",
    address: "Multiple SF locations",
    neighborhood: "Marina",
    description: "Club Card deals + gas rewards. Widespread in SF, reliable basics.",
    price_tier: 2,
    avg_price: 50,
    tags: ["chain", "rewards-program", "pharmacy"],
    lat: 37.7645,
    lng: -122.4320,
    status: "approved",
    vote_count: 21,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },

  // === BARS ===
  {
    id: "li-po-lounge",
    name: "Li Po Lounge",
    category: "bars",
    subcategory: "Dive Bar",
    address: "916 Grant Ave",
    neighborhood: "Chinatown",
    description: "Iconic dive, famous Chinese Mai Tai. Anthony Bourdain's SF favorite.",
    price_tier: 1,
    avg_price: 7,
    tags: ["dive-bar", "chinese-mai-tai"],
    lat: 37.7940,
    lng: -122.4076,
    status: "approved",
    vote_count: 59,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "the-500-club",
    name: "The 500 Club",
    category: "bars",
    subcategory: "Dive Bar",
    address: "500 Guerrero St",
    neighborhood: "Mission District",
    description: "Classic Mission dive, cheap wells, pool table. No pretense, just drinks.",
    price_tier: 1,
    avg_price: 7,
    tags: ["dive-bar", "pool-table"],
    lat: 37.7649,
    lng: -122.4236,
    status: "approved",
    vote_count: 44,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-21T00:00:00Z",
    updated_at: "2024-01-21T00:00:00Z",
  },
  {
    id: "toronado",
    name: "Toronado",
    category: "bars",
    subcategory: "Beer Bar",
    address: "547 Haight St",
    neighborhood: "Haight-Ashbury",
    description: "50+ craft beers on tap, SF institution. Cash only. The bartenders don't do cocktails.",
    price_tier: 1,
    avg_price: 8,
    tags: ["craft-beer", "local-icon"],
    lat: 37.7719,
    lng: -122.4296,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-01-22T00:00:00Z",
    updated_at: "2024-01-22T00:00:00Z",
  },

  // === GYM / FITNESS ===
  {
    id: "24-fitness-soma",
    name: "24 Hour Fitness - SoMa",
    category: "gym",
    subcategory: "Full Gym",
    address: "350 Bay St",
    neighborhood: "North Beach",
    description: "24/7 access, cardio, weights, group classes. One of the most affordable full-service gyms in SF.",
    price_tier: 2,
    avg_price: 35,
    tags: ["24-7", "classes", "cardio", "weights"],
    lat: 37.8058,
    lng: -122.4148,
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "24-fitness-fillmore",
    name: "24 Hour Fitness - Fillmore",
    category: "gym",
    subcategory: "Full Gym",
    address: "1200 Van Ness Ave",
    neighborhood: "Nob Hill",
    description: "Super Sport location with pool, basketball court, and sauna. Great value for the amenities.",
    price_tier: 2,
    avg_price: 40,
    tags: ["pool", "basketball", "sauna", "24-7"],
    lat: 37.7870,
    lng: -122.4213,
    status: "approved",
    vote_count: 45,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "24-fitness-market",
    name: "24 Hour Fitness - Market St",
    category: "gym",
    subcategory: "Full Gym",
    address: "100 14th St",
    neighborhood: "SoMa",
    description: "Convenient Market St location near BART. Solid equipment, busy during peak hours.",
    price_tier: 2,
    avg_price: 35,
    tags: ["near-BART", "cardio", "weights"],
    lat: 37.7678,
    lng: -122.4167,
    status: "approved",
    vote_count: 29,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-02T00:00:00Z",
    updated_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "crunch-fitness-sf",
    name: "Crunch Fitness",
    category: "gym",
    subcategory: "Full Gym",
    address: "61 New Montgomery St",
    neighborhood: "SoMa",
    description: "Budget-friendly full gym with group classes. Base membership starts around $30/month.",
    price_tier: 1,
    avg_price: 30,
    tags: ["budget", "classes", "downtown"],
    lat: 37.7878,
    lng: -122.4013,
    status: "approved",
    vote_count: 22,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-03T00:00:00Z",
    updated_at: "2024-02-03T00:00:00Z",
  },
  {
    id: "sf-rec-gyms",
    name: "SF Rec & Park Centers",
    category: "gym",
    subcategory: "Public Gym",
    address: "Multiple city rec centers",
    neighborhood: "SoMa",
    description: "City-run rec centers with fitness rooms. Free or very low-cost. Check sfrec.org for locations and schedules.",
    price_tier: 1,
    avg_price: 0,
    tags: ["public", "free", "low-cost"],
    lat: 37.7694,
    lng: -122.4262,
    status: "approved",
    vote_count: 41,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-04T00:00:00Z",
    updated_at: "2024-02-04T00:00:00Z",
  },
  {
    id: "outdoor-fitness",
    name: "Marina Green Fitness Court",
    category: "gym",
    subcategory: "Outdoor",
    address: "Marina Blvd & Scott St",
    neighborhood: "Marina",
    description: "Free outdoor fitness court with bodyweight stations, pull-up bars, and bay views. Also try the Lyon Street stairs.",
    price_tier: 1,
    avg_price: 0,
    tags: ["outdoor", "free", "bay-views", "bodyweight"],
    lat: 37.8065,
    lng: -122.4382,
    status: "approved",
    vote_count: 33,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-05T00:00:00Z",
    updated_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "ymca-embarcadero",
    name: "YMCA - Embarcadero",
    category: "gym",
    subcategory: "Full Gym",
    address: "169 Steuart St",
    neighborhood: "SoMa",
    description: "Full gym with pool, courts, and group classes. Sliding-scale pricing available based on income.",
    price_tier: 2,
    avg_price: 45,
    tags: ["pool", "sliding-scale", "classes", "courts"],
    lat: 37.7921,
    lng: -122.3923,
    status: "approved",
    vote_count: 27,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-06T00:00:00Z",
    updated_at: "2024-02-06T00:00:00Z",
  },

  // === COFFEE ===
  {
    id: "philz-coffee",
    name: "Philz Coffee",
    category: "coffee",
    subcategory: "Pour Over",
    address: "3101 24th St",
    neighborhood: "Mission District",
    description: "SF-born coffee legend. Every cup hand-crafted to order. The Tesora and Mint Mojito Iced are iconic. Multiple locations citywide.",
    price_tier: 1,
    avg_price: 5,
    tags: ["SF-born", "pour-over", "custom-blended", "local-icon"],
    lat: 37.7525,
    lng: -122.4180,
    status: "approved",
    vote_count: 72,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "blue-bottle",
    name: "Blue Bottle Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "66 Mint St",
    neighborhood: "SoMa",
    description: "Third-wave coffee pioneer. Minimalist design, meticulous pour-overs, single-origin beans. The Hayes Valley kiosk (315 Linden St) is the iconic original.",
    price_tier: 2,
    avg_price: 6,
    tags: ["third-wave", "minimalist", "single-origin", "design-forward"],
    lat: 37.7822,
    lng: -122.4074,
    status: "approved",
    vote_count: 65,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-11T00:00:00Z",
    updated_at: "2024-02-11T00:00:00Z",
  },
  {
    id: "ritual-coffee",
    name: "Ritual Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "1026 Valencia St",
    neighborhood: "Mission District",
    description: "OG SF third-wave roaster since 2005. Known for light roasts that highlight origin. Direct-trade sourcing with full transparency.",
    price_tier: 2,
    avg_price: 6,
    tags: ["third-wave-OG", "direct-trade", "light-roast", "Mission"],
    lat: 37.7565,
    lng: -122.4213,
    status: "approved",
    vote_count: 48,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-12T00:00:00Z",
    updated_at: "2024-02-12T00:00:00Z",
  },
  {
    id: "sightglass",
    name: "Sightglass Coffee",
    category: "coffee",
    subcategory: "Roastery Cafe",
    address: "270 7th St",
    neighborhood: "SoMa",
    description: "Jaw-dropping two-story warehouse space with visible roasting operation. One of the most photogenic coffee spots in the city.",
    price_tier: 2,
    avg_price: 6,
    tags: ["stunning-space", "roastery", "industrial", "photogenic"],
    lat: 37.7775,
    lng: -122.4065,
    status: "approved",
    vote_count: 55,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-13T00:00:00Z",
    updated_at: "2024-02-13T00:00:00Z",
  },
  {
    id: "equator-coffees",
    name: "Equator Coffees",
    category: "coffee",
    subcategory: "Specialty",
    address: "986 Market St",
    neighborhood: "SoMa",
    description: "Certified B-Corp, LGBTQ-owned. Deeply committed to sustainability and fair trade. Great coffee with real values behind the brand.",
    price_tier: 2,
    avg_price: 6,
    tags: ["B-Corp", "LGBTQ-owned", "sustainability", "direct-trade"],
    lat: 37.7818,
    lng: -122.4105,
    status: "approved",
    vote_count: 42,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "andytown",
    name: "Andytown Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "3655 Lawton St",
    neighborhood: "Outer Sunset",
    description: "Beloved Sunset shop with Irish roots. Famous for the Snowy Plover — espresso with whipped cream and brown sugar. Perfectly cozy for foggy days.",
    price_tier: 2,
    avg_price: 6,
    tags: ["Irish-influenced", "snowy-plover", "cozy", "Sunset-gem"],
    lat: 37.7566,
    lng: -122.4976,
    status: "approved",
    vote_count: 51,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "saint-frank",
    name: "Saint Frank Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "2340 Polk St",
    neighborhood: "Nob Hill",
    description: "Named after San Francisco's patron saint. Meticulous attention to detail, beautiful airy space, and exceptional direct-trade single-origin coffees.",
    price_tier: 2,
    avg_price: 6,
    tags: ["elegant", "precision", "direct-trade", "beautiful-space"],
    lat: 37.7988,
    lng: -122.4218,
    status: "approved",
    vote_count: 38,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-16T00:00:00Z",
    updated_at: "2024-02-16T00:00:00Z",
  },
  {
    id: "verve-coffee",
    name: "Verve Coffee Roasters",
    category: "coffee",
    subcategory: "Specialty",
    address: "2101 Market St",
    neighborhood: "Castro",
    description: "Santa Cruz-born roaster known for bright, fruit-forward coffees. Clean California-cool aesthetic. Strong farm relationships worldwide.",
    price_tier: 2,
    avg_price: 6,
    tags: ["bright-roasts", "California-cool", "specialty"],
    lat: 37.7679,
    lng: -122.4278,
    status: "approved",
    vote_count: 35,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-17T00:00:00Z",
    updated_at: "2024-02-17T00:00:00Z",
  },
  {
    id: "wrecking-ball",
    name: "Wrecking Ball Coffee",
    category: "coffee",
    subcategory: "Specialty",
    address: "2271 Union St",
    neighborhood: "Marina",
    description: "Founded by Trish Rothgeb who coined the term 'third wave coffee.' Light roasts that are complex and nuanced. A serious coffee nerd's dream.",
    price_tier: 2,
    avg_price: 6,
    tags: ["woman-owned", "light-roast", "third-wave-coiner"],
    lat: 37.7983,
    lng: -122.4365,
    status: "approved",
    vote_count: 30,
    votes_needed: 5,
    submitted_by: "community",
    created_at: "2024-02-18T00:00:00Z",
    updated_at: "2024-02-18T00:00:00Z",
  },

  // === PENDING (community submissions awaiting approval) ===
  {
    id: "pending-1",
    name: "New Thai Spot on Clement",
    category: "food",
    subcategory: "Thai",
    address: "512 Clement St",
    neighborhood: "Richmond",
    description: "Just opened last month. Amazing pad see ew for $13. Lunch specials under $10. BYOB on weekdays!",
    price_tier: 1,
    avg_price: 13,
    tags: ["new", "thai", "BYOB", "lunch-special"],
    lat: 37.7831,
    lng: -122.4657,
    status: "pending",
    vote_count: 3,
    votes_needed: 5,
    submitted_by: "user_abc123",
    created_at: "2024-03-20T00:00:00Z",
    updated_at: "2024-03-20T00:00:00Z",
  },
  {
    id: "pending-2",
    name: "Planet Fitness - Daly City",
    category: "gym",
    subcategory: "Budget Gym",
    address: "6400 Mission St, Daly City",
    neighborhood: "Other",
    description: "$10/month, 24/7. Basic but gets the job done. Right off BART.",
    price_tier: 1,
    avg_price: 10,
    tags: ["budget", "24-7", "near-BART"],
    lat: 37.7088,
    lng: -122.4528,
    status: "pending",
    vote_count: 2,
    votes_needed: 5,
    submitted_by: "user_def456",
    created_at: "2024-03-22T00:00:00Z",
    updated_at: "2024-03-22T00:00:00Z",
  },
  {
    id: "pending-3",
    name: "Sunset Produce Market",
    category: "grocery",
    subcategory: "Produce",
    address: "2226 Taraval St",
    neighborhood: "Sunset",
    description: "Incredible cheap produce. Way cheaper than Whole Foods. Family owned, been here for decades.",
    price_tier: 1,
    avg_price: 20,
    tags: ["produce", "family-owned", "cheap"],
    lat: 37.7432,
    lng: -122.4853,
    status: "pending",
    vote_count: 4,
    votes_needed: 5,
    submitted_by: "user_ghi789",
    created_at: "2024-03-25T00:00:00Z",
    updated_at: "2024-03-25T00:00:00Z",
  },
];
