-- Phase 4: Budgets, Savings Goals & Proactive Nudges
-- Tables, views, indexes, RLS policies, and realtime support

-- ============================================================
-- budgets: per-category spending limits
-- ============================================================
create table budgets (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    category    text not null,
    amount_limit double precision not null,
    period      text not null default 'monthly',
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

alter table budgets enable row level security;

create policy "Users can view their own budgets"
    on budgets for select
    using (auth.uid() = user_id);

create policy "Users can insert their own budgets"
    on budgets for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own budgets"
    on budgets for update
    using (auth.uid() = user_id);

create policy "Users can delete their own budgets"
    on budgets for delete
    using (auth.uid() = user_id);

-- ============================================================
-- savings_goals: user-defined savings targets
-- ============================================================
create table savings_goals (
    id              uuid primary key default gen_random_uuid(),
    user_id         uuid not null references auth.users(id) on delete cascade,
    name            text not null,
    target_amount   double precision not null,
    target_date     date,
    current_amount  double precision not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table savings_goals enable row level security;

create policy "Users can view their own savings goals"
    on savings_goals for select
    using (auth.uid() = user_id);

create policy "Users can insert their own savings goals"
    on savings_goals for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own savings goals"
    on savings_goals for update
    using (auth.uid() = user_id);

create policy "Users can delete their own savings goals"
    on savings_goals for delete
    using (auth.uid() = user_id);

-- ============================================================
-- notifications: alerts generated by nightly analysis
-- ============================================================
create table notifications (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    type        text not null,
    message     text not null,
    read        boolean not null default false,
    created_at  timestamptz not null default now()
);

alter table notifications enable row level security;

create policy "Users can view their own notifications"
    on notifications for select
    using (auth.uid() = user_id);

create policy "Users can update their own notifications"
    on notifications for update
    using (auth.uid() = user_id);

-- ============================================================
-- VIEW: monthly_spend_by_category
-- ============================================================
create or replace view monthly_spend_by_category as
select
    user_id,
    category,
    date_trunc('month', date) as month,
    sum(amount)               as total_spent,
    count(*)                  as tx_count
from transactions
where amount > 0
group by user_id, category, date_trunc('month', date);

-- ============================================================
-- VIEW: budget_status
-- ============================================================
create or replace view budget_status as
select
    b.id                                              as budget_id,
    b.user_id,
    b.category,
    b.amount_limit,
    b.period,
    coalesce(s.total_spent, 0)                        as spent,
    round((coalesce(s.total_spent, 0) / b.amount_limit * 100)::numeric, 1) as pct_used
from budgets b
left join (
    select user_id, category, sum(amount) as total_spent
    from transactions
    where amount > 0
      and date >= date_trunc('month', current_date)
    group by user_id, category
) s on b.user_id = s.user_id and b.category = s.category;

-- ============================================================
-- Indexes
-- ============================================================
create index idx_budgets_user_id on budgets(user_id);
create index idx_savings_goals_user_id on savings_goals(user_id);
create index idx_notifications_user_id on notifications(user_id);

-- ============================================================
-- Enable Realtime for new tables
-- ============================================================
alter publication supabase_realtime add table budgets;
alter publication supabase_realtime add table savings_goals;
